// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * VerificationFlow selects the preferred PIN or user-verification flow.
 */
export enum VerificationFlow {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * VerificationFlowDefault prefers built-in user verification with PIN fallback.
     */
    VerificationFlowDefault = "",

    /**
     * VerificationFlowPIN requests PIN verification first.
     */
    VerificationFlowPIN = "pin",
};
