// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Assessment is a static assessment of the information observable in one
 * authenticatorGetInfo response. Target is nil and no normative rules are run
 * when the response does not advertise a stable supported FIDO2 profile. It is
 * not a replacement for protocol-level certification testing.
 */
export class Assessment {
    "target": Target | null;
    "advertisedProfiles": Profile[];
    "findings": Finding[];
    "inconclusive": Inconclusive[];

    /** Creates a new Assessment instance. */
    constructor($$source: Partial<Assessment> = {}) {
        if (!("target" in $$source)) {
            this["target"] = null;
        }
        if (!("advertisedProfiles" in $$source)) {
            this["advertisedProfiles"] = [];
        }
        if (!("findings" in $$source)) {
            this["findings"] = [];
        }
        if (!("inconclusive" in $$source)) {
            this["inconclusive"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Assessment instance from a string or object.
     */
    static createFrom($$source: any = {}): Assessment {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType4;
        const $$createField3_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("target" in $$parsedSource) {
            $$parsedSource["target"] = $$createField0_0($$parsedSource["target"]);
        }
        if ("advertisedProfiles" in $$parsedSource) {
            $$parsedSource["advertisedProfiles"] = $$createField1_0($$parsedSource["advertisedProfiles"]);
        }
        if ("findings" in $$parsedSource) {
            $$parsedSource["findings"] = $$createField2_0($$parsedSource["findings"]);
        }
        if ("inconclusive" in $$parsedSource) {
            $$parsedSource["inconclusive"] = $$createField3_0($$parsedSource["inconclusive"]);
        }
        return new Assessment($$parsedSource as Partial<Assessment>);
    }
}

export class Evidence {
    "path": FieldPath;
    "state": EvidenceState;
    "values": string[];

    /** Creates a new Evidence instance. */
    constructor($$source: Partial<Evidence> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = EvidenceState.$zero;
        }
        if (!("values" in $$source)) {
            this["values"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Evidence instance from a string or object.
     */
    static createFrom($$source: any = {}): Evidence {
        const $$createField2_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("values" in $$parsedSource) {
            $$parsedSource["values"] = $$createField2_0($$parsedSource["values"]);
        }
        return new Evidence($$parsedSource as Partial<Evidence>);
    }
}

export enum EvidenceGapID {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    EvidenceGapAuthenticatorUIUnknown = "authenticator_ui_unknown",
    EvidenceGapImplicitCredProtectUnknown = "implicit_cred_protect_unknown",
    EvidenceGapBuiltInPINEntryUnknown = "built_in_pin_entry_unknown",
};

export enum EvidenceState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    EvidenceAbsent = "absent",
    EvidencePresentEmpty = "present_empty",
    EvidencePresent = "present",
    EvidenceFalse = "false",
    EvidenceTrue = "true",
    EvidenceValue = "value",
};

export class Expectation {
    "subjects": FieldPath[];
    "quantifier": ExpectationQuantifier;
    "kind": ExpectationKind;
    "values": string[];

    /** Creates a new Expectation instance. */
    constructor($$source: Partial<Expectation> = {}) {
        if (!("subjects" in $$source)) {
            this["subjects"] = [];
        }
        if (!("quantifier" in $$source)) {
            this["quantifier"] = ExpectationQuantifier.$zero;
        }
        if (!("kind" in $$source)) {
            this["kind"] = ExpectationKind.$zero;
        }
        if (!("values" in $$source)) {
            this["values"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Expectation instance from a string or object.
     */
    static createFrom($$source: any = {}): Expectation {
        const $$createField0_0 = $$createType8;
        const $$createField3_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("subjects" in $$parsedSource) {
            $$parsedSource["subjects"] = $$createField0_0($$parsedSource["subjects"]);
        }
        if ("values" in $$parsedSource) {
            $$parsedSource["values"] = $$createField3_0($$parsedSource["values"]);
        }
        return new Expectation($$parsedSource as Partial<Expectation>);
    }
}

export enum ExpectationKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ExpectationRequired = "required",
    ExpectationAbsent = "absent",
    ExpectationNonEmpty = "non_empty",
    ExpectationUnique = "unique",
    ExpectationMinimum = "minimum",
    ExpectationRange = "range",
    ExpectationContains = "contains",
    ExpectationExcludes = "excludes",
    ExpectationTrue = "true",
    ExpectationNotBoth = "not_both",
};

export enum ExpectationQuantifier {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ExpectationAll = "all",
    ExpectationAny = "any",
};

export type FieldPath = string;

export class Finding {
    "ruleId": RuleID;
    "profile": Profile;
    "expectations": Expectation[];
    "evidence": Evidence[];
    "references": RequirementRef[];

    /** Creates a new Finding instance. */
    constructor($$source: Partial<Finding> = {}) {
        if (!("ruleId" in $$source)) {
            this["ruleId"] = RuleID.$zero;
        }
        if (!("profile" in $$source)) {
            this["profile"] = Profile.$zero;
        }
        if (!("expectations" in $$source)) {
            this["expectations"] = [];
        }
        if (!("evidence" in $$source)) {
            this["evidence"] = [];
        }
        if (!("references" in $$source)) {
            this["references"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Finding instance from a string or object.
     */
    static createFrom($$source: any = {}): Finding {
        const $$createField2_0 = $$createType10;
        const $$createField3_0 = $$createType12;
        const $$createField4_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("expectations" in $$parsedSource) {
            $$parsedSource["expectations"] = $$createField2_0($$parsedSource["expectations"]);
        }
        if ("evidence" in $$parsedSource) {
            $$parsedSource["evidence"] = $$createField3_0($$parsedSource["evidence"]);
        }
        if ("references" in $$parsedSource) {
            $$parsedSource["references"] = $$createField4_0($$parsedSource["references"]);
        }
        return new Finding($$parsedSource as Partial<Finding>);
    }
}

export class Inconclusive {
    "ruleId": RuleID;
    "profile": Profile;
    "reason": EvidenceGapID;
    "expectations": Expectation[];
    "evidence": Evidence[];
    "references": RequirementRef[];

    /** Creates a new Inconclusive instance. */
    constructor($$source: Partial<Inconclusive> = {}) {
        if (!("ruleId" in $$source)) {
            this["ruleId"] = RuleID.$zero;
        }
        if (!("profile" in $$source)) {
            this["profile"] = Profile.$zero;
        }
        if (!("reason" in $$source)) {
            this["reason"] = EvidenceGapID.$zero;
        }
        if (!("expectations" in $$source)) {
            this["expectations"] = [];
        }
        if (!("evidence" in $$source)) {
            this["evidence"] = [];
        }
        if (!("references" in $$source)) {
            this["references"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Inconclusive instance from a string or object.
     */
    static createFrom($$source: any = {}): Inconclusive {
        const $$createField3_0 = $$createType10;
        const $$createField4_0 = $$createType12;
        const $$createField5_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("expectations" in $$parsedSource) {
            $$parsedSource["expectations"] = $$createField3_0($$parsedSource["expectations"]);
        }
        if ("evidence" in $$parsedSource) {
            $$parsedSource["evidence"] = $$createField4_0($$parsedSource["evidence"]);
        }
        if ("references" in $$parsedSource) {
            $$parsedSource["references"] = $$createField5_0($$parsedSource["references"]);
        }
        return new Inconclusive($$parsedSource as Partial<Inconclusive>);
    }
}

/**
 * Profile is an authenticator protocol profile advertised in GetInfo. A
 * profile is deliberately distinct from SpecificationID: the former is a
 * runtime claim while the latter identifies an immutable normative document.
 */
export enum Profile {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ProfileFIDO20 = "FIDO_2_0",
    ProfileFIDO21Pre = "FIDO_2_1_PRE",
    ProfileFIDO21 = "FIDO_2_1",
    ProfileFIDO23 = "FIDO_2_3",
    ProfileU2FV2 = "U2F_V2",
};

export type RequirementID = string;

export enum RequirementLevel {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RequirementConstraint = "CONSTRAINT",
    RequirementMust = "MUST",
    RequirementMustNot = "MUST_NOT",
};

export class RequirementRef {
    "id": RequirementID;
    "specification": SpecificationID;
    "section": string;
    "clause": string;
    "url": string;
    "level": RequirementLevel;

    /** Creates a new RequirementRef instance. */
    constructor($$source: Partial<RequirementRef> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("specification" in $$source)) {
            this["specification"] = SpecificationID.$zero;
        }
        if (!("section" in $$source)) {
            this["section"] = "";
        }
        if (!("clause" in $$source)) {
            this["clause"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("level" in $$source)) {
            this["level"] = RequirementLevel.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RequirementRef instance from a string or object.
     */
    static createFrom($$source: any = {}): RequirementRef {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RequirementRef($$parsedSource as Partial<RequirementRef>);
    }
}

export enum RuleID {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RuleVersionsRequired = "ctap.get_info.versions.required",
    RulePinUVAuthProtocolsNonEmpty = "ctap.get_info.pin_uv_auth_protocols.nonempty",
    RulePinUVAuthProtocolsUnique = "ctap.get_info.pin_uv_auth_protocols.unique",
    RuleTransportsNonEmpty = "ctap.get_info.transports.nonempty",
    RuleTransportsUnique = "ctap.get_info.transports.unique",
    RuleAlgorithmsNonEmpty = "ctap.get_info.algorithms.nonempty",
    RuleAlgorithmsUnique = "ctap.get_info.algorithms.unique",
    RuleTransportsForResetNonEmpty = "ctap.get_info.transports_for_reset.nonempty",
    RuleTransportsForResetUnique = "ctap.get_info.transports_for_reset.unique",
    RuleAttestationFormatsNonEmpty = "ctap.get_info.attestation_formats.nonempty",
    RuleAttestationFormatsUnique = "ctap.get_info.attestation_formats.unique",
    RuleAttestationFormatsNoneOmitted = "ctap.get_info.attestation_formats.none_omitted",
    RuleCertificationLevelRange = "ctap.get_info.certifications.level_range",
    RuleProfileHMACSecretRequired = "ctap.profile.hmac_secret.required",
    RuleProfileRKUVCapabilityRequired = "ctap.profile.rk.user_verification_capability_required",
    RuleProfileRKCredentialManagementRequired = "ctap.profile.rk.credential_management_required",
    RuleProfileCredentialProtectionRequired = "ctap.profile.user_verification.cred_protect_required",
    RuleProfilePinUVAuthTokenRequired = "ctap.profile.pin_uv_auth_token.required",
    RuleProfilePinUVProtocolTwoRequired = "ctap.profile.pin_uv_protocol_2.required",
    RuleCredBlobRequiresCredProtect = "ctap.get_info.cred_blob.cred_protect_required",
    RuleCredBlobRequiresMaxLength = "ctap.get_info.cred_blob.max_length_required",
    RuleCredBlobMaxLengthMinimum = "ctap.get_info.cred_blob.max_length_minimum",
    RuleCredBlobMaxLengthRequiresExtension = "ctap.get_info.cred_blob.max_length_requires_extension",
    RuleLargeBlobModesMutuallyExclusive = "ctap.get_info.large_blob.modes_mutually_exclusive",
    RuleLargeBlobExtensionsMutuallyExclusive = "ctap.get_info.large_blob.extensions_mutually_exclusive",
    RuleLargeBlobKeyRequiresCommand = "ctap.get_info.large_blob_key.command_required",
    RuleLargeBlobsRequiresCapacity = "ctap.get_info.large_blobs.capacity_required",
    RuleLargeBlobsCapacityMinimum = "ctap.get_info.large_blobs.capacity_minimum",
    RuleLargeBlobsCapacityRequiresCommand = "ctap.get_info.large_blobs.capacity_requires_command",
    RuleSetMinPINRequiresPINCapability = "ctap.get_info.set_min_pin_length.pin_capability_required",
    RuleSetMinPINSupportConsistency = "ctap.get_info.set_min_pin_length.support_consistency",
    RuleAuthenticatorConfigSupportConsistency = "ctap.get_info.authenticator_config.support_consistency",
    RuleConfigCommandRequired = "ctap.get_info.authenticator_config.command_required",
    RuleConfigCommandPrerequisite = "ctap.get_info.authenticator_config.command_prerequisite",
    RuleMinPINLengthMinimum = "ctap.get_info.min_pin_length.minimum",
    RuleMinPINLengthRequiresClientPIN = "ctap.get_info.min_pin_length.requires_client_pin",
    RuleClientPINRequiresMinPINLength = "ctap.get_info.client_pin.min_pin_length_required",
    RuleMaxPINLengthMinimum = "ctap.get_info.max_pin_length.minimum",
    RuleMaxPINLengthRequiresClientPIN = "ctap.get_info.max_pin_length.requires_client_pin",
    RulePinComplexityRequiresClientPIN = "ctap.get_info.pin_complexity.requires_client_pin",
    RuleNoMCGARequiresClientPIN = "ctap.get_info.no_mc_ga_permissions.requires_client_pin",
    RuleUVBioEnrollRequiresBioEnroll = "ctap.get_info.uv_bio_enroll.requires_bio_enroll",
    RuleUVAcfgRequiresAuthnrCfg = "ctap.get_info.uv_acfg.requires_authnr_cfg",
    RuleAlwaysUVConflictsWithMakeCredUVNotRqd = "ctap.get_info.always_uv.conflicts_with_make_cred_uv_not_required",
    RuleAlwaysUVU2FRequiresBuiltInUV = "ctap.get_info.always_uv.u2f_requires_built_in_uv",
};

/**
 * Source identifies the upstream artifact from which a suite was adapted.
 * Digest is the digest of the complete artifact, including the algorithm
 * prefix, for example "sha256:...".
 */
export class Source {
    "artifact": string;
    "version": string;
    "digest"?: string;

    /** Creates a new Source instance. */
    constructor($$source: Partial<Source> = {}) {
        if (!("artifact" in $$source)) {
            this["artifact"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Source instance from a string or object.
     */
    static createFrom($$source: any = {}): Source {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Source($$parsedSource as Partial<Source>);
    }
}

/**
 * SourceLocation maps a test back to its exact upstream case.
 */
export class SourceLocation {
    "path": string;
    "case": string;

    /** Creates a new SourceLocation instance. */
    constructor($$source: Partial<SourceLocation> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("case" in $$source)) {
            this["case"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SourceLocation instance from a string or object.
     */
    static createFrom($$source: any = {}): SourceLocation {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SourceLocation($$parsedSource as Partial<SourceLocation>);
    }
}

export enum SpecificationID {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SpecificationCTAP20 = "ctap-2.0-ps-20190130",
    SpecificationCTAP21 = "ctap-2.1-ps-20210615",
    SpecificationCTAP23 = "ctap-2.3-ps-20260226",
};

/**
 * Status is the aggregate outcome of a suite, test, or step.
 */
export enum Status {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusPassed = "passed",
    StatusFailed = "failed",
    StatusSkipped = "skipped",
    StatusError = "error",
};

/**
 * StepID is the stable identifier of one phase within a test.
 */
export type StepID = string;

/**
 * StepResult is the structured result of one executed step.
 */
export class StepResult {
    "id": StepID;
    "name": string;
    "references": RequirementRef[];
    "status": Status;
    "message"?: string;

    /** Creates a new StepResult instance. */
    constructor($$source: Partial<StepResult> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("references" in $$source)) {
            this["references"] = [];
        }
        if (!("status" in $$source)) {
            this["status"] = Status.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StepResult instance from a string or object.
     */
    static createFrom($$source: any = {}): StepResult {
        const $$createField2_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("references" in $$parsedSource) {
            $$parsedSource["references"] = $$createField2_0($$parsedSource["references"]);
        }
        return new StepResult($$parsedSource as Partial<StepResult>);
    }
}

/**
 * SuiteID is the stable identifier of an executable conformance suite.
 */
export type SuiteID = string;

/**
 * SuiteResult is the complete structured result of one suite run.
 */
export class SuiteResult {
    "id": SuiteID;
    "name": string;
    "description"?: string;
    "source": Source;
    "status": Status;
    "error"?: string;
    "tests": TestResult[];

    /** Creates a new SuiteResult instance. */
    constructor($$source: Partial<SuiteResult> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = (new Source());
        }
        if (!("status" in $$source)) {
            this["status"] = Status.$zero;
        }
        if (!("tests" in $$source)) {
            this["tests"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SuiteResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SuiteResult {
        const $$createField3_0 = $$createType15;
        const $$createField6_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("source" in $$parsedSource) {
            $$parsedSource["source"] = $$createField3_0($$parsedSource["source"]);
        }
        if ("tests" in $$parsedSource) {
            $$parsedSource["tests"] = $$createField6_0($$parsedSource["tests"]);
        }
        return new SuiteResult($$parsedSource as Partial<SuiteResult>);
    }
}

export class Target {
    "specification": SpecificationID;
    "profile": Profile;

    /** Creates a new Target instance. */
    constructor($$source: Partial<Target> = {}) {
        if (!("specification" in $$source)) {
            this["specification"] = SpecificationID.$zero;
        }
        if (!("profile" in $$source)) {
            this["profile"] = Profile.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Target instance from a string or object.
     */
    static createFrom($$source: any = {}): Target {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Target($$parsedSource as Partial<Target>);
    }
}

/**
 * TestID is the stable identifier of one independently reported test.
 */
export type TestID = string;

/**
 * TestResult is the structured result of one test.
 */
export class TestResult {
    "id": TestID;
    "name": string;
    "description"?: string;
    "source": SourceLocation;
    "references": RequirementRef[];
    "status": Status;
    "steps": StepResult[];

    /** Creates a new TestResult instance. */
    constructor($$source: Partial<TestResult> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = (new SourceLocation());
        }
        if (!("references" in $$source)) {
            this["references"] = [];
        }
        if (!("status" in $$source)) {
            this["status"] = Status.$zero;
        }
        if (!("steps" in $$source)) {
            this["steps"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TestResult instance from a string or object.
     */
    static createFrom($$source: any = {}): TestResult {
        const $$createField3_0 = $$createType18;
        const $$createField4_0 = $$createType14;
        const $$createField6_0 = $$createType20;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("source" in $$parsedSource) {
            $$parsedSource["source"] = $$createField3_0($$parsedSource["source"]);
        }
        if ("references" in $$parsedSource) {
            $$parsedSource["references"] = $$createField4_0($$parsedSource["references"]);
        }
        if ("steps" in $$parsedSource) {
            $$parsedSource["steps"] = $$createField6_0($$parsedSource["steps"]);
        }
        return new TestResult($$parsedSource as Partial<TestResult>);
    }
}

// Private type creation functions
const $$createType0 = Target.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = Finding.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = Inconclusive.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $Create.Array($Create.Any);
const $$createType8 = $Create.Array($Create.Any);
const $$createType9 = Expectation.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = Evidence.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = RequirementRef.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = Source.createFrom;
const $$createType16 = TestResult.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = SourceLocation.createFrom;
const $$createType19 = StepResult.createFrom;
const $$createType20 = $Create.Array($$createType19);
