// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as protocol$0 from "../../../ctap/protocol/models.js";

/**
 * Metadata is the expected authenticator declaration used by metadata-bound
 * conformance checks. GetInfoFields records exact CBOR field presence so false
 * and zero values remain distinguishable from absent fields.
 */
export class Metadata {
    "getInfo": protocol$0.AuthenticatorGetInfoResponse;
    "getInfoFields": number[];
    "userVerificationMethods": protocol$0.UserVerify;

    /** Creates a new Metadata instance. */
    constructor($$source: Partial<Metadata> = {}) {
        if (!("getInfo" in $$source)) {
            this["getInfo"] = (new protocol$0.AuthenticatorGetInfoResponse());
        }
        if (!("getInfoFields" in $$source)) {
            this["getInfoFields"] = [];
        }
        if (!("userVerificationMethods" in $$source)) {
            this["userVerificationMethods"] = protocol$0.UserVerify.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Metadata instance from a string or object.
     */
    static createFrom($$source: any = {}): Metadata {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("getInfo" in $$parsedSource) {
            $$parsedSource["getInfo"] = $$createField0_0($$parsedSource["getInfo"]);
        }
        if ("getInfoFields" in $$parsedSource) {
            $$parsedSource["getInfoFields"] = $$createField1_0($$parsedSource["getInfoFields"]);
        }
        return new Metadata($$parsedSource as Partial<Metadata>);
    }
}

/**
 * RunMode selects the non-destructive or complete Authr-Generic-1 test set.
 */
export enum RunMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * RunModeSafe is the zero-value mode and runs P-1 through P-3 without
     * resetting the authenticator.
     */
    RunModeSafe = "",

    /**
     * RunModeFull runs P-1 through P-5. P-4 and P-5 may each factory-reset
     * the authenticator when their encrypted GetInfo member is advertised.
     */
    RunModeFull = "full",
};

// Private type creation functions
const $$createType0 = protocol$0.AuthenticatorGetInfoResponse.createFrom;
const $$createType1 = $Create.Array($Create.Any);
