// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as key$0 from "../../../../ldclabs/cose/key/models.js";

/**
 * ExtensionIdentifier is an enum consisting of IANA registered Extension Identifiers.
 * https://www.iana.org/assignments/webauthn/webauthn.xhtml
 */
export enum ExtensionIdentifier {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ExtensionIdentifierAppID = "appid",
    ExtensionIdentifierTxAuthSimple = "txAuthSimple",
    ExtensionIdentifierTxAuthGeneric = "txAuthGeneric",
    ExtensionIdentifierAuthnSelection = "authnSel",
    ExtensionIdentifierExtensions = "exts",
    ExtensionIdentifierUserVerificationIndex = "uvi",
    ExtensionIdentifierLocation = "loc",
    ExtensionIdentifierUserVerificationMethod = "uvm",
    ExtensionIdentifierCredentialProtection = "credProtect",
    ExtensionIdentifierCredentialBlob = "credBlob",
    ExtensionIdentifierLargeBlobKey = "largeBlobKey",
    ExtensionIdentifierMinPinLength = "minPinLength",
    ExtensionIdentifierPinComplexityPolicy = "pinComplexityPolicy",
    ExtensionIdentifierHMACSecret = "hmac-secret",
    ExtensionIdentifierHMACSecretMC = "hmac-secret-mc",
    ExtensionIdentifierAppIDExclude = "appidExclude",
    ExtensionIdentifierCredentialProperties = "credProps",
    ExtensionIdentifierLargeBlob = "largeBlob",
    ExtensionIdentifierPayment = "payment",
};

/**
 * PublicKeyCredentialParameters is used to supply additional parameters when creating a new credential.
 * https://www.w3.org/TR/webauthn-3/#dictdef-publickeycredentialparameters
 */
export class PublicKeyCredentialParameters {
    "type": PublicKeyCredentialType;
    "alg": key$0.Alg;

    /** Creates a new PublicKeyCredentialParameters instance. */
    constructor($$source: Partial<PublicKeyCredentialParameters> = {}) {
        if (!("type" in $$source)) {
            this["type"] = PublicKeyCredentialType.$zero;
        }
        if (!("alg" in $$source)) {
            this["alg"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PublicKeyCredentialParameters instance from a string or object.
     */
    static createFrom($$source: any = {}): PublicKeyCredentialParameters {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PublicKeyCredentialParameters($$parsedSource as Partial<PublicKeyCredentialParameters>);
    }
}

/**
 * PublicKeyCredentialType defines the valid credential types.
 * https://www.w3.org/TR/webauthn-3/#enumdef-publickeycredentialtype
 */
export enum PublicKeyCredentialType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PublicKeyCredentialTypePublicKey = "public-key",
};
