// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Capability is a bitmap of applications exposed by a YubiKey interface.
 */
export enum Capability {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    CapabilityOTP = 1,
    CapabilityU2F = 2,
    CapabilityCCID = 4,
    CapabilityOpenPGP = 8,
    CapabilityPIV = 16,
    CapabilityOATH = 32,
    CapabilityHSMAuth = 256,
    CapabilityCTAP2 = 512,
};

/**
 * DeviceInfo is returned by Yubico's GET DEVICE INFORMATION command.
 * UnknownFields preserves tags introduced by newer firmware.
 */
export class DeviceInfo {
    "supportedUSBCapabilities": Capability;
    "serial"?: number | null;
    "enabledUSBCapabilities": Capability;
    "formFactor": FormFactor;
    "isFIPS": boolean;
    "isSecurityKey": boolean;
    "firmwareVersion": FirmwareVersion;
    "versionQualifier"?: VersionQualifier | null;
    "autoEjectTimeout": number;
    "challengeResponseTimeout": number;
    "deviceFlags": number;
    "locked": boolean;
    "partNumber"?: string | null;
    "fipsCapable": Capability;
    "fipsApproved": Capability;
    "pinComplexity": boolean;
    "nfcRestricted": boolean;
    "resetBlocked": Capability;
    "fpsVersion"?: FirmwareVersion | null;
    "stmVersion"?: FirmwareVersion | null;
    "supportedNFCCapabilities"?: Capability | null;
    "enabledNFCCapabilities"?: Capability | null;
    "unknownFields": { [_ in `${number}`]?: string };

    /** Creates a new DeviceInfo instance. */
    constructor($$source: Partial<DeviceInfo> = {}) {
        if (!("supportedUSBCapabilities" in $$source)) {
            this["supportedUSBCapabilities"] = Capability.$zero;
        }
        if (!("enabledUSBCapabilities" in $$source)) {
            this["enabledUSBCapabilities"] = Capability.$zero;
        }
        if (!("formFactor" in $$source)) {
            this["formFactor"] = FormFactor.$zero;
        }
        if (!("isFIPS" in $$source)) {
            this["isFIPS"] = false;
        }
        if (!("isSecurityKey" in $$source)) {
            this["isSecurityKey"] = false;
        }
        if (!("firmwareVersion" in $$source)) {
            this["firmwareVersion"] = (new FirmwareVersion());
        }
        if (!("autoEjectTimeout" in $$source)) {
            this["autoEjectTimeout"] = 0;
        }
        if (!("challengeResponseTimeout" in $$source)) {
            this["challengeResponseTimeout"] = 0;
        }
        if (!("deviceFlags" in $$source)) {
            this["deviceFlags"] = 0;
        }
        if (!("locked" in $$source)) {
            this["locked"] = false;
        }
        if (!("fipsCapable" in $$source)) {
            this["fipsCapable"] = Capability.$zero;
        }
        if (!("fipsApproved" in $$source)) {
            this["fipsApproved"] = Capability.$zero;
        }
        if (!("pinComplexity" in $$source)) {
            this["pinComplexity"] = false;
        }
        if (!("nfcRestricted" in $$source)) {
            this["nfcRestricted"] = false;
        }
        if (!("resetBlocked" in $$source)) {
            this["resetBlocked"] = Capability.$zero;
        }
        if (!("unknownFields" in $$source)) {
            this["unknownFields"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): DeviceInfo {
        const $$createField6_0 = $$createType0;
        const $$createField7_0 = $$createType2;
        const $$createField18_0 = $$createType3;
        const $$createField19_0 = $$createType3;
        const $$createField22_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("firmwareVersion" in $$parsedSource) {
            $$parsedSource["firmwareVersion"] = $$createField6_0($$parsedSource["firmwareVersion"]);
        }
        if ("versionQualifier" in $$parsedSource) {
            $$parsedSource["versionQualifier"] = $$createField7_0($$parsedSource["versionQualifier"]);
        }
        if ("fpsVersion" in $$parsedSource) {
            $$parsedSource["fpsVersion"] = $$createField18_0($$parsedSource["fpsVersion"]);
        }
        if ("stmVersion" in $$parsedSource) {
            $$parsedSource["stmVersion"] = $$createField19_0($$parsedSource["stmVersion"]);
        }
        if ("unknownFields" in $$parsedSource) {
            $$parsedSource["unknownFields"] = $$createField22_0($$parsedSource["unknownFields"]);
        }
        return new DeviceInfo($$parsedSource as Partial<DeviceInfo>);
    }
}

/**
 * FirmwareVersion is the major.minor.build version reported by the device.
 */
export class FirmwareVersion {
    "major": number;
    "minor": number;
    "build": number;

    /** Creates a new FirmwareVersion instance. */
    constructor($$source: Partial<FirmwareVersion> = {}) {
        if (!("major" in $$source)) {
            this["major"] = 0;
        }
        if (!("minor" in $$source)) {
            this["minor"] = 0;
        }
        if (!("build" in $$source)) {
            this["build"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FirmwareVersion instance from a string or object.
     */
    static createFrom($$source: any = {}): FirmwareVersion {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FirmwareVersion($$parsedSource as Partial<FirmwareVersion>);
    }
}

/**
 * FormFactor describes the physical shape and connector type of a YubiKey.
 */
export enum FormFactor {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    FormFactorUnknown = 0,
    FormFactorUSBAKeychain = 1,
    FormFactorUSBANano = 2,
    FormFactorUSBCKeychain = 3,
    FormFactorUSBCNano = 4,
    FormFactorUSBCLightning = 5,
    FormFactorUSBABiometricKeychain = 6,
    FormFactorUSBCBiometricKeychain = 7,
};

/**
 * ReleaseType identifies the release stage of qualified firmware.
 */
export enum ReleaseType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    ReleaseTypeAlpha = 0,
    ReleaseTypeBeta = 1,
    ReleaseTypeFinal = 2,
};

/**
 * VersionQualifier contains the behavioral firmware version reported by
 * development firmware.
 */
export class VersionQualifier {
    "version": FirmwareVersion;
    "releaseType": ReleaseType;
    "iteration": number;

    /** Creates a new VersionQualifier instance. */
    constructor($$source: Partial<VersionQualifier> = {}) {
        if (!("version" in $$source)) {
            this["version"] = (new FirmwareVersion());
        }
        if (!("releaseType" in $$source)) {
            this["releaseType"] = ReleaseType.$zero;
        }
        if (!("iteration" in $$source)) {
            this["iteration"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VersionQualifier instance from a string or object.
     */
    static createFrom($$source: any = {}): VersionQualifier {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("version" in $$parsedSource) {
            $$parsedSource["version"] = $$createField0_0($$parsedSource["version"]);
        }
        return new VersionQualifier($$parsedSource as Partial<VersionQualifier>);
    }
}

// Private type creation functions
const $$createType0 = FirmwareVersion.createFrom;
const $$createType1 = VersionQualifier.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Nullable($$createType0);
const $$createType4 = $Create.Map($Create.Any, $Create.ByteSlice);
