// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Capability is a bitmap of applications exposed by a YubiKey interface.
 */
export enum Capability {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    CapabilityOTP = 1,
    CapabilityU2F = 2,
    CapabilityCCID = 4,
    CapabilityOpenPGP = 8,
    CapabilityPIV = 16,
    CapabilityOATH = 32,
    CapabilityHSMAuth = 256,
    CapabilityCTAP2 = 512,
};

/**
 * DeviceInfo is returned by Yubico's GET DEVICE INFORMATION command.
 * UnknownFields preserves tags introduced by newer firmware.
 */
export class DeviceInfo {
    "SupportedUSBCapabilities": Capability;
    "Serial": number | null;
    "EnabledUSBCapabilities": Capability;
    "FormFactor": FormFactor;
    "IsFIPS": boolean;
    "IsSecurityKey": boolean;
    "FirmwareVersion": FirmwareVersion;
    "VersionQualifier": VersionQualifier | null;
    "AutoEjectTimeout": number;
    "ChallengeResponseTimeout": number;
    "DeviceFlags": number;
    "Locked": boolean;
    "PartNumber": string | null;
    "FIPSCapable": Capability;
    "FIPSApproved": Capability;
    "PinComplexity": boolean;
    "NFCRestricted": boolean;
    "ResetBlocked": Capability;
    "FPSVersion": FirmwareVersion | null;
    "STMVersion": FirmwareVersion | null;
    "SupportedNFCCapabilities": Capability | null;
    "EnabledNFCCapabilities": Capability | null;
    "UnknownFields": { [_ in `${number}`]?: string };

    /** Creates a new DeviceInfo instance. */
    constructor($$source: Partial<DeviceInfo> = {}) {
        if (!("SupportedUSBCapabilities" in $$source)) {
            this["SupportedUSBCapabilities"] = Capability.$zero;
        }
        if (!("Serial" in $$source)) {
            this["Serial"] = null;
        }
        if (!("EnabledUSBCapabilities" in $$source)) {
            this["EnabledUSBCapabilities"] = Capability.$zero;
        }
        if (!("FormFactor" in $$source)) {
            this["FormFactor"] = FormFactor.$zero;
        }
        if (!("IsFIPS" in $$source)) {
            this["IsFIPS"] = false;
        }
        if (!("IsSecurityKey" in $$source)) {
            this["IsSecurityKey"] = false;
        }
        if (!("FirmwareVersion" in $$source)) {
            this["FirmwareVersion"] = (new FirmwareVersion());
        }
        if (!("VersionQualifier" in $$source)) {
            this["VersionQualifier"] = null;
        }
        if (!("AutoEjectTimeout" in $$source)) {
            this["AutoEjectTimeout"] = 0;
        }
        if (!("ChallengeResponseTimeout" in $$source)) {
            this["ChallengeResponseTimeout"] = 0;
        }
        if (!("DeviceFlags" in $$source)) {
            this["DeviceFlags"] = 0;
        }
        if (!("Locked" in $$source)) {
            this["Locked"] = false;
        }
        if (!("PartNumber" in $$source)) {
            this["PartNumber"] = null;
        }
        if (!("FIPSCapable" in $$source)) {
            this["FIPSCapable"] = Capability.$zero;
        }
        if (!("FIPSApproved" in $$source)) {
            this["FIPSApproved"] = Capability.$zero;
        }
        if (!("PinComplexity" in $$source)) {
            this["PinComplexity"] = false;
        }
        if (!("NFCRestricted" in $$source)) {
            this["NFCRestricted"] = false;
        }
        if (!("ResetBlocked" in $$source)) {
            this["ResetBlocked"] = Capability.$zero;
        }
        if (!("FPSVersion" in $$source)) {
            this["FPSVersion"] = null;
        }
        if (!("STMVersion" in $$source)) {
            this["STMVersion"] = null;
        }
        if (!("SupportedNFCCapabilities" in $$source)) {
            this["SupportedNFCCapabilities"] = null;
        }
        if (!("EnabledNFCCapabilities" in $$source)) {
            this["EnabledNFCCapabilities"] = null;
        }
        if (!("UnknownFields" in $$source)) {
            this["UnknownFields"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): DeviceInfo {
        const $$createField6_0 = $$createType0;
        const $$createField7_0 = $$createType2;
        const $$createField18_0 = $$createType3;
        const $$createField19_0 = $$createType3;
        const $$createField22_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("FirmwareVersion" in $$parsedSource) {
            $$parsedSource["FirmwareVersion"] = $$createField6_0($$parsedSource["FirmwareVersion"]);
        }
        if ("VersionQualifier" in $$parsedSource) {
            $$parsedSource["VersionQualifier"] = $$createField7_0($$parsedSource["VersionQualifier"]);
        }
        if ("FPSVersion" in $$parsedSource) {
            $$parsedSource["FPSVersion"] = $$createField18_0($$parsedSource["FPSVersion"]);
        }
        if ("STMVersion" in $$parsedSource) {
            $$parsedSource["STMVersion"] = $$createField19_0($$parsedSource["STMVersion"]);
        }
        if ("UnknownFields" in $$parsedSource) {
            $$parsedSource["UnknownFields"] = $$createField22_0($$parsedSource["UnknownFields"]);
        }
        return new DeviceInfo($$parsedSource as Partial<DeviceInfo>);
    }
}

/**
 * FirmwareVersion is the major.minor.build version reported by the device.
 */
export class FirmwareVersion {
    "Major": number;
    "Minor": number;
    "Build": number;

    /** Creates a new FirmwareVersion instance. */
    constructor($$source: Partial<FirmwareVersion> = {}) {
        if (!("Major" in $$source)) {
            this["Major"] = 0;
        }
        if (!("Minor" in $$source)) {
            this["Minor"] = 0;
        }
        if (!("Build" in $$source)) {
            this["Build"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FirmwareVersion instance from a string or object.
     */
    static createFrom($$source: any = {}): FirmwareVersion {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FirmwareVersion($$parsedSource as Partial<FirmwareVersion>);
    }
}

/**
 * FormFactor describes the physical shape and connector type of a YubiKey.
 */
export enum FormFactor {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    FormFactorUnknown = 0,
    FormFactorUSBAKeychain = 1,
    FormFactorUSBANano = 2,
    FormFactorUSBCKeychain = 3,
    FormFactorUSBCNano = 4,
    FormFactorUSBCLightning = 5,
    FormFactorUSBABiometricKeychain = 6,
    FormFactorUSBCBiometricKeychain = 7,
};

/**
 * ReleaseType identifies the release stage of qualified firmware.
 */
export enum ReleaseType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    ReleaseTypeAlpha = 0,
    ReleaseTypeBeta = 1,
    ReleaseTypeFinal = 2,
};

/**
 * VersionQualifier contains the behavioral firmware version reported by
 * development firmware.
 */
export class VersionQualifier {
    "Version": FirmwareVersion;
    "ReleaseType": ReleaseType;
    "Iteration": number;

    /** Creates a new VersionQualifier instance. */
    constructor($$source: Partial<VersionQualifier> = {}) {
        if (!("Version" in $$source)) {
            this["Version"] = (new FirmwareVersion());
        }
        if (!("ReleaseType" in $$source)) {
            this["ReleaseType"] = ReleaseType.$zero;
        }
        if (!("Iteration" in $$source)) {
            this["Iteration"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VersionQualifier instance from a string or object.
     */
    static createFrom($$source: any = {}): VersionQualifier {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Version" in $$parsedSource) {
            $$parsedSource["Version"] = $$createField0_0($$parsedSource["Version"]);
        }
        return new VersionQualifier($$parsedSource as Partial<VersionQualifier>);
    }
}

// Private type creation functions
const $$createType0 = FirmwareVersion.createFrom;
const $$createType1 = VersionQualifier.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Nullable($$createType0);
const $$createType4 = $Create.Map($Create.Any, $Create.ByteSlice);
