// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {$models.BioEnrollRequest} req
 * @returns {$CancellablePromise<$models.OperationEnvelope>}
 */
export function BioEnroll(req) {
    return $Call.ByID(578408764, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.OperationRequest} req
 * @returns {$CancellablePromise<$models.OperationEnvelope>}
 */
export function BioList(req) {
    return $Call.ByID(2116388904, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.BioMutationRequest} req
 * @returns {$CancellablePromise<$models.OperationEnvelope>}
 */
export function BioRemove(req) {
    return $Call.ByID(2160820328, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.BioMutationRequest} req
 * @returns {$CancellablePromise<$models.OperationEnvelope>}
 */
export function BioRename(req) {
    return $Call.ByID(2546413730, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.OperationRequest} req
 * @returns {$CancellablePromise<$models.OperationEnvelope>}
 */
export function BioSensorInfo(req) {
    return $Call.ByID(632558830, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} operationID
 * @returns {$CancellablePromise<boolean>}
 */
export function CancelOperation(operationID) {
    return $Call.ByID(1085839797, operationID);
}

/**
 * @param {$models.PINRequest} req
 * @returns {$CancellablePromise<$models.OperationEnvelope>}
 */
export function ChangePIN(req) {
    return $Call.ByID(2523362617, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.OperationRequest} req
 * @returns {$CancellablePromise<$models.OperationEnvelope>}
 */
export function ConfigStatus(req) {
    return $Call.ByID(3347953682, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.CredentialDeleteRequest} req
 * @returns {$CancellablePromise<$models.OperationEnvelope>}
 */
export function DeleteCredential(req) {
    return $Call.ByID(2232281028, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.LargeBlobMutationRequest} req
 * @returns {$CancellablePromise<$models.OperationEnvelope>}
 */
export function DeleteLargeBlob(req) {
    return $Call.ByID(1219988499, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.DiscoverRequest} req
 * @returns {$CancellablePromise<$models.DiscoveryResponse>}
 */
export function Discover(req) {
    return $Call.ByID(2207120457, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.GetAssertionRequest} req
 * @returns {$CancellablePromise<$models.OperationEnvelope>}
 */
export function GetAssertion(req) {
    return $Call.ByID(3190035102, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.OperationRequest} req
 * @returns {$CancellablePromise<$models.OperationEnvelope>}
 */
export function Inspect(req) {
    return $Call.ByID(2429534602, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.OperationRequest} req
 * @returns {$CancellablePromise<$models.OperationEnvelope>}
 */
export function ListCredentials(req) {
    return $Call.ByID(3503039332, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.OperationRequest} req
 * @returns {$CancellablePromise<$models.OperationEnvelope>}
 */
export function ListLargeBlobs(req) {
    return $Call.ByID(61833203, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.MakeCredentialRequest} req
 * @returns {$CancellablePromise<$models.OperationEnvelope>}
 */
export function MakeCredential(req) {
    return $Call.ByID(312151421, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.LargeBlobReadRequest} req
 * @returns {$CancellablePromise<$models.OperationEnvelope>}
 */
export function ReadLargeBlob(req) {
    return $Call.ByID(3190122286, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.ResetRequest} req
 * @returns {$CancellablePromise<$models.OperationEnvelope>}
 */
export function ResetFactory(req) {
    return $Call.ByID(3965535905, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.InteractionAnswer} answer
 * @returns {$CancellablePromise<boolean>}
 */
export function ResolveInteraction(answer) {
    return $Call.ByID(1745500846, answer);
}

/**
 * @param {string} selector
 * @returns {$CancellablePromise<$models.DiscoveryResponse>}
 */
export function Select(selector) {
    return $Call.ByID(274961134, selector).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.AlwaysUVRequest} req
 * @returns {$CancellablePromise<$models.OperationEnvelope>}
 */
export function SetAlwaysUV(req) {
    return $Call.ByID(2725868996, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.MinPINLengthRequest} req
 * @returns {$CancellablePromise<$models.OperationEnvelope>}
 */
export function SetMinPINLength(req) {
    return $Call.ByID(2689413465, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.PINRequest} req
 * @returns {$CancellablePromise<$models.OperationEnvelope>}
 */
export function SetPIN(req) {
    return $Call.ByID(3432981285, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.CredentialUpdateRequest} req
 * @returns {$CancellablePromise<$models.OperationEnvelope>}
 */
export function UpdateCredentialUser(req) {
    return $Call.ByID(1217761801, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.LargeBlobMutationRequest} req
 * @returns {$CancellablePromise<$models.OperationEnvelope>}
 */
export function WriteLargeBlob(req) {
    return $Call.ByID(1732664211, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.OperationEnvelope.createFrom;
const $$createType1 = $models.DiscoveryResponse.createFrom;
