// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Algorithm identifies an entry in the IANA COSE Algorithms registry.
 */
export enum Algorithm {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    /**
     * AlgorithmES256 is ECDSA with SHA-256 on the P-256 curve.
     */
    AlgorithmES256 = -7,

    /**
     * AlgorithmECDHESHKDF256 is ECDH ES with HKDF-SHA-256.
     */
    AlgorithmECDHESHKDF256 = -25,
};
