//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as service$0 from "../../../../../telesma/service/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "ctapkit:discovery-changed": $$createType0,
        "ctapkit:interaction-requested": $$createType1,
        "ctapkit:logs-changed": $$createType2,
        "ctapkit:operation-event": $$createType3,
    }));
}

// Private type creation functions
const $$createType0 = service$0.DiscoveryChangedEnvelope.createFrom;
const $$createType1 = service$0.InteractionPrompt.createFrom;
const $$createType2 = service$0.LogCursor.createFrom;
const $$createType3 = service$0.OperationEventEnvelope.createFrom;

configure();
