//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as main$0 from "../../../../../changeme/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "authenticator:interaction-requested": $$createType0,
        "authenticator:interaction-resolved": $$createType1,
        "authenticator:operation-progress": $$createType2,
    }));
}

// Private type creation functions
const $$createType0 = main$0.InteractionPrompt.createFrom;
const $$createType1 = main$0.InteractionAnswer.createFrom;
const $$createType2 = main$0.OperationEventEnvelope.createFrom;

configure();
