// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as service$0 from "../../../../go-ctap/kit/service/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "ctapkit:discovery-changed": service$0.DiscoveryChangedEnvelope;
            "ctapkit:interaction-requested": service$0.InteractionPrompt;
            "ctapkit:operation-event": service$0.OperationEventEnvelope;
        }
    }
}
