// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ApplicationConfig {
    "locale": string;
    "advancedMode": boolean;
    "passkeyDirectoryEnabled": boolean;

    /** Creates a new ApplicationConfig instance. */
    constructor($$source: Partial<ApplicationConfig> = {}) {
        if (!("locale" in $$source)) {
            this["locale"] = "";
        }
        if (!("advancedMode" in $$source)) {
            this["advancedMode"] = false;
        }
        if (!("passkeyDirectoryEnabled" in $$source)) {
            this["passkeyDirectoryEnabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ApplicationConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ApplicationConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ApplicationConfig($$parsedSource as Partial<ApplicationConfig>);
    }
}

export class ApplicationConfigSnapshot {
    "config": ApplicationConfig;
    "exists": boolean;

    /** Creates a new ApplicationConfigSnapshot instance. */
    constructor($$source: Partial<ApplicationConfigSnapshot> = {}) {
        if (!("config" in $$source)) {
            this["config"] = (new ApplicationConfig());
        }
        if (!("exists" in $$source)) {
            this["exists"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ApplicationConfigSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): ApplicationConfigSnapshot {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField0_0($$parsedSource["config"]);
        }
        return new ApplicationConfigSnapshot($$parsedSource as Partial<ApplicationConfigSnapshot>);
    }
}

export class ApplicationInfo {
    "version": string;

    /** Creates a new ApplicationInfo instance. */
    constructor($$source: Partial<ApplicationInfo> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ApplicationInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ApplicationInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ApplicationInfo($$parsedSource as Partial<ApplicationInfo>);
    }
}

// Private type creation functions
const $$createType0 = ApplicationConfig.createFrom;
