// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetApplicationInfo(): $CancellablePromise<$models.ApplicationInfo> {
    return $Call.ByID(741992745).then(($result: any) => {
        return $$createType0($result);
    });
}

export function LoadApplicationConfig(): $CancellablePromise<$models.ApplicationConfigSnapshot> {
    return $Call.ByID(2064344301).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SaveApplicationConfig(config: $models.ApplicationConfig): $CancellablePromise<void> {
    return $Call.ByID(4199412390, config);
}

// Private type creation functions
const $$createType0 = $models.ApplicationInfo.createFrom;
const $$createType1 = $models.ApplicationConfigSnapshot.createFrom;
