// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    Assertion,
    AuthenticatorOptions,
    CredentialBlobCreateOutput,
    CredentialBlobGetOutput,
    CredentialProtectionOutput,
    GetAssertionClientExtensionResults,
    GetAssertionExtensionResults,
    GetAssertionInput,
    GetAssertionPRFOutput,
    GetAssertionPreview,
    GetAssertionResult,
    HMACSecretCreateOutput,
    HMACSecretOutput,
    MakeCredentialAuthenticatorExtensionOutputs,
    MakeCredentialClientExtensionResults,
    MakeCredentialExtensionResults,
    MakeCredentialInput,
    MakeCredentialPRFOutput,
    MakeCredentialPreview,
    MakeCredentialResult,
    MinPINLengthOutput,
    PINComplexityPolicyOutput
} from "./models.js";
