// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AuthenticatorOptions {
    "residentKey"?: boolean | null;
    "userPresence"?: boolean | null;
    "userVerification"?: boolean | null;

    /** Creates a new AuthenticatorOptions instance. */
    constructor($$source: Partial<AuthenticatorOptions> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AuthenticatorOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): AuthenticatorOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AuthenticatorOptions($$parsedSource as Partial<AuthenticatorOptions>);
    }
}

export class CredentialDescriptor {
    "type"?: string;
    "credentialIDHex": string;
    "transports"?: string[];

    /** Creates a new CredentialDescriptor instance. */
    constructor($$source: Partial<CredentialDescriptor> = {}) {
        if (!("credentialIDHex" in $$source)) {
            this["credentialIDHex"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CredentialDescriptor instance from a string or object.
     */
    static createFrom($$source: any = {}): CredentialDescriptor {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("transports" in $$parsedSource) {
            $$parsedSource["transports"] = $$createField2_0($$parsedSource["transports"]);
        }
        return new CredentialDescriptor($$parsedSource as Partial<CredentialDescriptor>);
    }
}

export class CredentialParameter {
    "type"?: string;
    "alg": number;

    /** Creates a new CredentialParameter instance. */
    constructor($$source: Partial<CredentialParameter> = {}) {
        if (!("alg" in $$source)) {
            this["alg"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CredentialParameter instance from a string or object.
     */
    static createFrom($$source: any = {}): CredentialParameter {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CredentialParameter($$parsedSource as Partial<CredentialParameter>);
    }
}

export class RelyingParty {
    "id": string;
    "name"?: string;

    /** Creates a new RelyingParty instance. */
    constructor($$source: Partial<RelyingParty> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RelyingParty instance from a string or object.
     */
    static createFrom($$source: any = {}): RelyingParty {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RelyingParty($$parsedSource as Partial<RelyingParty>);
    }
}

export class User {
    "userIDHex"?: string;
    "name"?: string;
    "displayName"?: string;

    /** Creates a new User instance. */
    constructor($$source: Partial<User> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new User instance from a string or object.
     */
    static createFrom($$source: any = {}): User {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new User($$parsedSource as Partial<User>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
