// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AuthenticatorOptions {
    /**
     * Creates a new AuthenticatorOptions instance.
     * @param {Partial<AuthenticatorOptions>} [$$source = {}] - The source object to create the AuthenticatorOptions.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | null | undefined}
             */
            this["residentKey"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | null | undefined}
             */
            this["userPresence"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | null | undefined}
             */
            this["userVerification"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AuthenticatorOptions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AuthenticatorOptions}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AuthenticatorOptions(/** @type {Partial<AuthenticatorOptions>} */($$parsedSource));
    }
}

export class CredentialDescriptor {
    /**
     * Creates a new CredentialDescriptor instance.
     * @param {Partial<CredentialDescriptor>} [$$source = {}] - The source object to create the CredentialDescriptor.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["type"] = undefined;
        }
        if (!("credentialIDHex" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["credentialIDHex"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["transports"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CredentialDescriptor instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CredentialDescriptor}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("transports" in $$parsedSource) {
            $$parsedSource["transports"] = $$createField2_0($$parsedSource["transports"]);
        }
        return new CredentialDescriptor(/** @type {Partial<CredentialDescriptor>} */($$parsedSource));
    }
}

export class CredentialParameter {
    /**
     * Creates a new CredentialParameter instance.
     * @param {Partial<CredentialParameter>} [$$source = {}] - The source object to create the CredentialParameter.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["type"] = undefined;
        }
        if (!("alg" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["alg"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CredentialParameter instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CredentialParameter}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CredentialParameter(/** @type {Partial<CredentialParameter>} */($$parsedSource));
    }
}

export class GetAssertionInput {
    /**
     * Creates a new GetAssertionInput instance.
     * @param {Partial<GetAssertionInput>} [$$source = {}] - The source object to create the GetAssertionInput.
     */
    constructor($$source = {}) {
        if (!("rpID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["rpID"] = "";
        }
        if (!("clientDataJSON" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["clientDataJSON"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {CredentialDescriptor[] | undefined}
             */
            this["allowList"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {AuthenticatorOptions | undefined}
             */
            this["options"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetAssertionInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GetAssertionInput}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $Create.ByteSlice;
        const $$createField2_0 = $$createType2;
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("clientDataJSON" in $$parsedSource) {
            $$parsedSource["clientDataJSON"] = $$createField1_0($$parsedSource["clientDataJSON"]);
        }
        if ("allowList" in $$parsedSource) {
            $$parsedSource["allowList"] = $$createField2_0($$parsedSource["allowList"]);
        }
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField3_0($$parsedSource["options"]);
        }
        return new GetAssertionInput(/** @type {Partial<GetAssertionInput>} */($$parsedSource));
    }
}

export class MakeCredentialInput {
    /**
     * Creates a new MakeCredentialInput instance.
     * @param {Partial<MakeCredentialInput>} [$$source = {}] - The source object to create the MakeCredentialInput.
     */
    constructor($$source = {}) {
        if (!("rp" in $$source)) {
            /**
             * @member
             * @type {RelyingParty}
             */
            this["rp"] = (new RelyingParty());
        }
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {User}
             */
            this["user"] = (new User());
        }
        if (!("clientDataJSON" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["clientDataJSON"] = "";
        }
        if (!("pubKeyCredParams" in $$source)) {
            /**
             * @member
             * @type {CredentialParameter[]}
             */
            this["pubKeyCredParams"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {CredentialDescriptor[] | undefined}
             */
            this["excludeList"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {AuthenticatorOptions | undefined}
             */
            this["options"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MakeCredentialInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MakeCredentialInput}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType4;
        const $$createField1_0 = $$createType5;
        const $$createField2_0 = $Create.ByteSlice;
        const $$createField3_0 = $$createType7;
        const $$createField4_0 = $$createType2;
        const $$createField5_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("rp" in $$parsedSource) {
            $$parsedSource["rp"] = $$createField0_0($$parsedSource["rp"]);
        }
        if ("user" in $$parsedSource) {
            $$parsedSource["user"] = $$createField1_0($$parsedSource["user"]);
        }
        if ("clientDataJSON" in $$parsedSource) {
            $$parsedSource["clientDataJSON"] = $$createField2_0($$parsedSource["clientDataJSON"]);
        }
        if ("pubKeyCredParams" in $$parsedSource) {
            $$parsedSource["pubKeyCredParams"] = $$createField3_0($$parsedSource["pubKeyCredParams"]);
        }
        if ("excludeList" in $$parsedSource) {
            $$parsedSource["excludeList"] = $$createField4_0($$parsedSource["excludeList"]);
        }
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField5_0($$parsedSource["options"]);
        }
        return new MakeCredentialInput(/** @type {Partial<MakeCredentialInput>} */($$parsedSource));
    }
}

export class RelyingParty {
    /**
     * Creates a new RelyingParty instance.
     * @param {Partial<RelyingParty>} [$$source = {}] - The source object to create the RelyingParty.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["name"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RelyingParty instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RelyingParty}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RelyingParty(/** @type {Partial<RelyingParty>} */($$parsedSource));
    }
}

export class User {
    /**
     * Creates a new User instance.
     * @param {Partial<User>} [$$source = {}] - The source object to create the User.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["userIDHex"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["name"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["displayName"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new User instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {User}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new User(/** @type {Partial<User>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = CredentialDescriptor.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = AuthenticatorOptions.createFrom;
const $$createType4 = RelyingParty.createFrom;
const $$createType5 = User.createFrom;
const $$createType6 = CredentialParameter.createFrom;
const $$createType7 = $Create.Array($$createType6);
