// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CTAPDetail records the exact authenticator command and status associated with
 * a failure. Numeric values remain authoritative for unknown extension and
 * vendor values whose symbolic names are unavailable.
 */
export class CTAPDetail {
    "command"?: string;
    "commandCode": number;
    "subCommandFamily"?: string;
    "subCommand"?: string;
    "subCommandCode"?: number | null;
    "status"?: string;
    "statusCode": number;

    /** Creates a new CTAPDetail instance. */
    constructor($$source: Partial<CTAPDetail> = {}) {
        if (!("commandCode" in $$source)) {
            this["commandCode"] = 0;
        }
        if (!("statusCode" in $$source)) {
            this["statusCode"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CTAPDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): CTAPDetail {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CTAPDetail($$parsedSource as Partial<CTAPDetail>);
    }
}

/**
 * Category groups failure codes for coarse recovery behavior.
 */
export enum Category {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CategoryUnsupported = "unsupported",
    CategoryPermissionDenied = "permission-denied",
    CategoryTransportFailure = "transport-failure",
    CategoryTimeout = "timeout",
    CategoryBusy = "busy",
    CategoryInvalidSession = "invalid-session",
    CategoryInvalidOperation = "invalid-operation",
    CategoryInvalidState = "invalid-state",
    CategoryCanceled = "canceled",
    CategoryInternal = "internal",
};

/**
 * Code identifies one stable, machine-readable failure condition.
 */
export enum Code {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CodeInternalError = "INTERNAL_ERROR",
    CodeOperationRequired = "OPERATION_REQUIRED",
    CodeOperationUnsupported = "OPERATION_UNSUPPORTED",
    CodeOperationCanceled = "OPERATION_CANCELED",
    CodeOperationTimeout = "OPERATION_TIMEOUT",
    CodeRequestJSONInvalid = "REQUEST_JSON_INVALID",
    CodeConfirmationRequired = "CONFIRMATION_REQUIRED",
    CodeVerificationFlowUnsupported = "VERIFICATION_FLOW_UNSUPPORTED",
    CodeInteractionKindRequired = "INTERACTION_KIND_REQUIRED",
    CodeInteractionHandlerRequired = "INTERACTION_HANDLER_REQUIRED",
    CodeInteractionCanceled = "INTERACTION_CANCELED",
    CodeSessionInvalid = "SESSION_INVALID",
    CodeSessionClosed = "SESSION_CLOSED",
    CodeServiceClosed = "SERVICE_CLOSED",
    CodeDeviceHandleInvalid = "DEVICE_HANDLE_INVALID",
    CodeDeviceNotFound = "DEVICE_NOT_FOUND",
    CodeDeviceSelectionRequired = "DEVICE_SELECTION_REQUIRED",
    CodeDeviceUnavailable = "DEVICE_UNAVAILABLE",
    CodeTransportModeUnsupported = "TRANSPORT_MODE_UNSUPPORTED",
    CodeTransportPermissionDenied = "TRANSPORT_PERMISSION_DENIED",
    CodeTransportProxyUnavailable = "TRANSPORT_PROXY_UNAVAILABLE",
    CodeTransportFailure = "TRANSPORT_FAILURE",
    CodeMDSAAGUIDInvalid = "MDS_AAGUID_INVALID",
    CodeMDSFetchFailed = "MDS_FETCH_FAILED",
    CodeMDSVerificationFailed = "MDS_VERIFICATION_FAILED",
    CodeConformanceTargetInvalid = "CONFORMANCE_TARGET_INVALID",
    CodeRelyingPartyIDRequired = "RELYING_PARTY_ID_REQUIRED",
    CodeUserIDRequired = "USER_ID_REQUIRED",
    CodeClientDataJSONRequired = "CLIENT_DATA_JSON_REQUIRED",
    CodePublicKeyCredentialParametersRequired = "PUBLIC_KEY_CREDENTIAL_PARAMETERS_REQUIRED",
    CodePublicKeyCredentialAlgorithmRequired = "PUBLIC_KEY_CREDENTIAL_ALGORITHM_REQUIRED",
    CodeCredentialIDRequired = "CREDENTIAL_ID_REQUIRED",
    CodeCredentialNotFound = "CREDENTIAL_NOT_FOUND",
    CodeCredentialExcluded = "CREDENTIAL_EXCLUDED",
    CodeCredentialStoreFull = "CREDENTIAL_STORE_FULL",
    CodeCredentialManagementUnsupported = "CREDENTIAL_MANAGEMENT_UNSUPPORTED",
    CodeCredentialChangesRequired = "CREDENTIAL_CHANGES_REQUIRED",
    CodeUserIDHexInvalid = "USER_ID_HEX_INVALID",
    CodeAttestedCredentialDataMissing = "ATTESTED_CREDENTIAL_DATA_MISSING",
    CodeCredentialCreationDenied = "CREDENTIAL_CREATION_DENIED",
    CodeAssertionDenied = "ASSERTION_DENIED",
    CodeAssertionNotAllowed = "ASSERTION_NOT_ALLOWED",
    CodeAssertionContinuationUnavailable = "ASSERTION_CONTINUATION_UNAVAILABLE",
    CodePINUnsupported = "PIN_UNSUPPORTED",
    CodePINAlreadyConfigured = "PIN_ALREADY_CONFIGURED",
    CodePINNotConfigured = "PIN_NOT_CONFIGURED",
    CodePINRequired = "PIN_REQUIRED",
    CodePINInvalid = "PIN_INVALID",
    CodePINBlocked = "PIN_BLOCKED",
    CodePINUVAuthInvalid = "PIN_UV_AUTH_INVALID",
    CodePINUVAuthBlocked = "PIN_UV_AUTH_BLOCKED",
    CodePINPolicyViolation = "PIN_POLICY_VIOLATION",
    CodePINUVAuthTokenRequired = "PIN_UV_AUTH_TOKEN_REQUIRED",
    CodePINUVPermissionUnauthorized = "PIN_UV_PERMISSION_UNAUTHORIZED",
    CodeUserPresenceRequired = "USER_PRESENCE_REQUIRED",
    CodeUserVerificationBlocked = "USER_VERIFICATION_BLOCKED",
    CodeUserVerificationInvalid = "USER_VERIFICATION_INVALID",
    CodeBioUnsupported = "BIO_UNSUPPORTED",
    CodeBioTemplateIDRequired = "BIO_TEMPLATE_ID_REQUIRED",
    CodeBioTemplateIDInvalid = "BIO_TEMPLATE_ID_INVALID",
    CodeBioNoEnrollments = "BIO_NO_ENROLLMENTS",
    CodeBioEnrollmentNotFound = "BIO_ENROLLMENT_NOT_FOUND",
    CodeBioDatabaseFull = "BIO_DATABASE_FULL",
    CodeAuthenticatorConfigUnsupported = "AUTHENTICATOR_CONFIG_UNSUPPORTED",
    CodeAuthenticatorConfigStorageFull = "AUTHENTICATOR_CONFIG_STORAGE_FULL",
    CodeAuthenticatorOperationDenied = "AUTHENTICATOR_OPERATION_DENIED",
    CodeAuthenticatorOperationNotAllowed = "AUTHENTICATOR_OPERATION_NOT_ALLOWED",
    CodeAlwaysUVStateUnknown = "ALWAYS_UV_STATE_UNKNOWN",
    CodeAlwaysUVAlreadyTarget = "ALWAYS_UV_ALREADY_TARGET",
    CodeMinPINLengthUnsupported = "MIN_PIN_LENGTH_UNSUPPORTED",
    CodeMinPINLengthDecreaseNotAllowed = "MIN_PIN_LENGTH_DECREASE_NOT_ALLOWED",
    CodeResetWindowExpired = "RESET_WINDOW_EXPIRED",
    CodeResetTouchTimeout = "RESET_TOUCH_TIMEOUT",
    CodeLargeBlobUnsupported = "LARGE_BLOB_UNSUPPORTED",
    CodeLargeBlobKeyMissing = "LARGE_BLOB_KEY_MISSING",
    CodeLargeBlobArrayTooLarge = "LARGE_BLOB_ARRAY_TOO_LARGE",
    CodeLargeBlobStorageFull = "LARGE_BLOB_STORAGE_FULL",
    CodeLargeBlobArrayInvalid = "LARGE_BLOB_ARRAY_INVALID",
    CodeLargeBlobWriteSequenceInvalid = "LARGE_BLOB_WRITE_SEQUENCE_INVALID",
    CodeLargeBlobIntegrityFailure = "LARGE_BLOB_INTEGRITY_FAILURE",
    CodeLargeBlobMissing = "LARGE_BLOB_MISSING",
    CodeLargeBlobUTF8Invalid = "LARGE_BLOB_UTF8_INVALID",
    CodeLargeBlobJSONInvalid = "LARGE_BLOB_JSON_INVALID",
    CodeLargeBlobCBORInvalid = "LARGE_BLOB_CBOR_INVALID",
    CodeLargeBlobDecodeModeUnsupported = "LARGE_BLOB_DECODE_MODE_UNSUPPORTED",
    CodeCTAPCommandInvalid = "CTAP_COMMAND_INVALID",
    CodeCTAPParameterInvalid = "CTAP_PARAMETER_INVALID",
    CodeCTAPLengthInvalid = "CTAP_LENGTH_INVALID",
    CodeCTAPSequenceInvalid = "CTAP_SEQUENCE_INVALID",
    CodeAuthenticatorTimeout = "AUTHENTICATOR_TIMEOUT",
    CodeAuthenticatorBusy = "AUTHENTICATOR_BUSY",
    CodeCTAPLockRequired = "CTAP_LOCK_REQUIRED",
    CodeCTAPChannelInvalid = "CTAP_CHANNEL_INVALID",
    CodeCTAPCBORTypeInvalid = "CTAP_CBOR_TYPE_INVALID",
    CodeCTAPCBORInvalid = "CTAP_CBOR_INVALID",
    CodeCTAPParameterMissing = "CTAP_PARAMETER_MISSING",
    CodeCTAPLimitExceeded = "CTAP_LIMIT_EXCEEDED",
    CodeAuthenticatorProcessing = "AUTHENTICATOR_PROCESSING",
    CodeCredentialInvalid = "CREDENTIAL_INVALID",
    CodeUserActionPending = "USER_ACTION_PENDING",
    CodeAuthenticatorOperationPending = "AUTHENTICATOR_OPERATION_PENDING",
    CodeAuthenticatorNoOperations = "AUTHENTICATOR_NO_OPERATIONS",
    CodeAlgorithmUnsupported = "ALGORITHM_UNSUPPORTED",
    CodeCTAPOptionUnsupported = "CTAP_OPTION_UNSUPPORTED",
    CodeCTAPOptionInvalid = "CTAP_OPTION_INVALID",
    CodeAuthenticatorOperationCanceled = "AUTHENTICATOR_OPERATION_CANCELED",
    CodeUserActionTimeout = "USER_ACTION_TIMEOUT",
    CodeCTAPRequestTooLarge = "CTAP_REQUEST_TOO_LARGE",
    CodeAuthenticatorActionTimeout = "AUTHENTICATOR_ACTION_TIMEOUT",
    CodeCTAPIntegrityFailure = "CTAP_INTEGRITY_FAILURE",
    CodeCTAPSubcommandInvalid = "CTAP_SUBCOMMAND_INVALID",
    CodeCTAPOtherError = "CTAP_OTHER_ERROR",
    CodeCTAPReservedStatus = "CTAP_RESERVED_STATUS",
    CodeCTAPExtensionError = "CTAP_EXTENSION_ERROR",
    CodeCTAPVendorError = "CTAP_VENDOR_ERROR",
    CodeGetInfoUnsupported = "GET_INFO_UNSUPPORTED",
    CodeAuthenticatorSelectionTimeout = "AUTHENTICATOR_SELECTION_TIMEOUT",
    CodeAuthenticatorSelectionCanceled = "AUTHENTICATOR_SELECTION_CANCELED",
    CodeBioInteractionTimeout = "BIO_INTERACTION_TIMEOUT",
};

/**
 * Failure is the transport-safe, machine-readable representation of one
 * failure. It intentionally contains no human-readable message or Go cause.
 */
export class Failure {
    "code": Code;
    "category": Category;
    "params"?: { [_ in string]?: string };
    "operation"?: string;
    "phase"?: Phase;
    "ctap"?: CTAPDetail | null;

    /** Creates a new Failure instance. */
    constructor($$source: Partial<Failure> = {}) {
        if (!("code" in $$source)) {
            this["code"] = Code.$zero;
        }
        if (!("category" in $$source)) {
            this["category"] = Category.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Failure instance from a string or object.
     */
    static createFrom($$source: any = {}): Failure {
        const $$createField2_0 = $$createType0;
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("params" in $$parsedSource) {
            $$parsedSource["params"] = $$createField2_0($$parsedSource["params"]);
        }
        if ("ctap" in $$parsedSource) {
            $$parsedSource["ctap"] = $$createField5_0($$parsedSource["ctap"]);
        }
        return new Failure($$parsedSource as Partial<Failure>);
    }
}

/**
 * Phase identifies the runtime phase in which a failure occurred.
 */
export enum Phase {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PhaseValidation = "validation",
    PhaseDiscovery = "discovery",
    PhaseSession = "session",
    PhaseInteraction = "interaction",
    PhaseTokenAcquisition = "token-acquisition",
    PhaseAuthenticatorCommand = "authenticator-command",
    PhaseAssertionContinuation = "assertion-continuation",
    PhaseMetadata = "metadata",
    PhaseDecode = "decode",
    PhaseCleanup = "cleanup",
};

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = CTAPDetail.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
