// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Alg represents an IANA algorithm entry in the COSE Algorithms registry.
 * 
 * Reference https://www.iana.org/assignments/cose/cose.xhtml#algorithms
 */
export type Alg = number;
