// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class PasskeyDirectoryLookupRequest {
    "rpIDs": string[];

    /** Creates a new PasskeyDirectoryLookupRequest instance. */
    constructor($$source: Partial<PasskeyDirectoryLookupRequest> = {}) {
        if (!("rpIDs" in $$source)) {
            this["rpIDs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PasskeyDirectoryLookupRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): PasskeyDirectoryLookupRequest {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("rpIDs" in $$parsedSource) {
            $$parsedSource["rpIDs"] = $$createField0_0($$parsedSource["rpIDs"]);
        }
        return new PasskeyDirectoryLookupRequest($$parsedSource as Partial<PasskeyDirectoryLookupRequest>);
    }
}

export class PasskeyDirectoryLookupResult {
    "matches": PasskeyDirectoryMatch[];

    /** Creates a new PasskeyDirectoryLookupResult instance. */
    constructor($$source: Partial<PasskeyDirectoryLookupResult> = {}) {
        if (!("matches" in $$source)) {
            this["matches"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PasskeyDirectoryLookupResult instance from a string or object.
     */
    static createFrom($$source: any = {}): PasskeyDirectoryLookupResult {
        const $$createField0_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("matches" in $$parsedSource) {
            $$parsedSource["matches"] = $$createField0_0($$parsedSource["matches"]);
        }
        return new PasskeyDirectoryLookupResult($$parsedSource as Partial<PasskeyDirectoryLookupResult>);
    }
}

export class PasskeyDirectoryMatch {
    "rpID": string;
    "canonicalDomain": string;
    "passwordless"?: PasskeySupportMode | null;
    "mfa"?: PasskeySupportMode | null;
    "documentation"?: string;
    "recovery"?: string;
    "notes"?: string;

    /** Creates a new PasskeyDirectoryMatch instance. */
    constructor($$source: Partial<PasskeyDirectoryMatch> = {}) {
        if (!("rpID" in $$source)) {
            this["rpID"] = "";
        }
        if (!("canonicalDomain" in $$source)) {
            this["canonicalDomain"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PasskeyDirectoryMatch instance from a string or object.
     */
    static createFrom($$source: any = {}): PasskeyDirectoryMatch {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PasskeyDirectoryMatch($$parsedSource as Partial<PasskeyDirectoryMatch>);
    }
}

/**
 * PasskeySupportMode describes whether one Passkey Directory capability is
 * available or mandatory for the listed service.
 */
export enum PasskeySupportMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PasskeySupportModeAllowed = "allowed",
    PasskeySupportModeRequired = "required",
};

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = PasskeyDirectoryMatch.createFrom;
const $$createType2 = $Create.Array($$createType1);
