// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as failure$0 from "./failure/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as operation$0 from "./operation/models.js";

export enum InteractionKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    InteractionKindPIN = "pin",
    InteractionKindUserVerification = "user-verification",
    InteractionKindTouch = "touch",
};

export class InteractionRequest {
    "kind": InteractionKind;
    "message"?: string;
    "permission"?: string;
    "destructive"?: boolean;
    "preview"?: any;
    "pinState"?: PINInteractionState | null;

    /** Creates a new InteractionRequest instance. */
    constructor($$source: Partial<InteractionRequest> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = InteractionKind.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InteractionRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): InteractionRequest {
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("pinState" in $$parsedSource) {
            $$parsedSource["pinState"] = $$createField5_0($$parsedSource["pinState"]);
        }
        return new InteractionRequest($$parsedSource as Partial<InteractionRequest>);
    }
}

export class LogEntry {
    "timestamp": string;
    "durationMilliseconds"?: number;
    "outcome": LogOutcome;
    "operationKind"?: operation$0.Kind;
    "command"?: string;
    "commandCode"?: number;
    "subCommand"?: string;
    "subCommandCode"?: number | null;
    "request"?: LogPayload | null;
    "response"?: LogPayload | null;
    "error"?: failure$0.Failure | null;
    "errorMessage"?: string;
    "redactedFields"?: string[];

    /** Creates a new LogEntry instance. */
    constructor($$source: Partial<LogEntry> = {}) {
        if (!("timestamp" in $$source)) {
            this["timestamp"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("outcome" in $$source)) {
            this["outcome"] = LogOutcome.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): LogEntry {
        const $$createField8_0 = $$createType3;
        const $$createField9_0 = $$createType3;
        const $$createField10_0 = $$createType5;
        const $$createField12_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("request" in $$parsedSource) {
            $$parsedSource["request"] = $$createField8_0($$parsedSource["request"]);
        }
        if ("response" in $$parsedSource) {
            $$parsedSource["response"] = $$createField9_0($$parsedSource["response"]);
        }
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField10_0($$parsedSource["error"]);
        }
        if ("redactedFields" in $$parsedSource) {
            $$parsedSource["redactedFields"] = $$createField12_0($$parsedSource["redactedFields"]);
        }
        return new LogEntry($$parsedSource as Partial<LogEntry>);
    }
}

export class LogJournalBatch {
    "entries": LogJournalRecord[];
    "cursor": number;
    "truncated"?: boolean;

    /** Creates a new LogJournalBatch instance. */
    constructor($$source: Partial<LogJournalBatch> = {}) {
        if (!("entries" in $$source)) {
            this["entries"] = [];
        }
        if (!("cursor" in $$source)) {
            this["cursor"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogJournalBatch instance from a string or object.
     */
    static createFrom($$source: any = {}): LogJournalBatch {
        const $$createField0_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField0_0($$parsedSource["entries"]);
        }
        return new LogJournalBatch($$parsedSource as Partial<LogJournalBatch>);
    }
}

export class LogJournalRecord {
    "sequence": number;
    "entry": LogEntry;

    /** Creates a new LogJournalRecord instance. */
    constructor($$source: Partial<LogJournalRecord> = {}) {
        if (!("sequence" in $$source)) {
            this["sequence"] = 0;
        }
        if (!("entry" in $$source)) {
            this["entry"] = (new LogEntry());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogJournalRecord instance from a string or object.
     */
    static createFrom($$source: any = {}): LogJournalRecord {
        const $$createField1_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entry" in $$parsedSource) {
            $$parsedSource["entry"] = $$createField1_0($$parsedSource["entry"]);
        }
        return new LogJournalRecord($$parsedSource as Partial<LogJournalRecord>);
    }
}

export enum LogOutcome {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    LogOutcomeSucceeded = "succeeded",
    LogOutcomeFailed = "failed",
    LogOutcomeCanceled = "canceled",
};

export class LogPayload {
    "cborDiagnostic"?: string;
    "diagnosticError"?: string;
    "originalBytes": number;
    "storedBytes": number;
    "truncated": boolean;

    /** Creates a new LogPayload instance. */
    constructor($$source: Partial<LogPayload> = {}) {
        if (!("originalBytes" in $$source)) {
            this["originalBytes"] = 0;
        }
        if (!("storedBytes" in $$source)) {
            this["storedBytes"] = 0;
        }
        if (!("truncated" in $$source)) {
            this["truncated"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): LogPayload {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogPayload($$parsedSource as Partial<LogPayload>);
    }
}

export class OperationEvent {
    "stage": OperationStage;
    "kind"?: InteractionKind;
    "message"?: string;
    "completed"?: number | null;
    "total"?: number | null;
    "sampleStatus"?: string;

    /** Creates a new OperationEvent instance. */
    constructor($$source: Partial<OperationEvent> = {}) {
        if (!("stage" in $$source)) {
            this["stage"] = OperationStage.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OperationEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): OperationEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OperationEvent($$parsedSource as Partial<OperationEvent>);
    }
}

export enum OperationStage {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    OperationStageInteractionRequired = "interaction-required",
    OperationStageEnumeratingRPs = "enumerating-rps",
    OperationStageEnumeratingCredentials = "enumerating-credentials",
    OperationStageCapturingBioSample = "capturing-bio-sample",
};

export class PINInteractionState {
    "failure"?: failure$0.Failure | null;
    "retriesRemaining"?: number | null;
    "powerCycleState"?: boolean | null;

    /** Creates a new PINInteractionState instance. */
    constructor($$source: Partial<PINInteractionState> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PINInteractionState instance from a string or object.
     */
    static createFrom($$source: any = {}): PINInteractionState {
        const $$createField0_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("failure" in $$parsedSource) {
            $$parsedSource["failure"] = $$createField0_0($$parsedSource["failure"]);
        }
        return new PINInteractionState($$parsedSource as Partial<PINInteractionState>);
    }
}

export enum VerificationFlow {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    VerificationFlowDefault = "",
    VerificationFlowPIN = "pin",
};

// Private type creation functions
const $$createType0 = PINInteractionState.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = LogPayload.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = failure$0.Failure.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($Create.Any);
const $$createType7 = LogJournalRecord.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = LogEntry.createFrom;
