// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as credential$0 from "../../ctap/credential/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as extension$0 from "../../ctap/extension/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as protocol$0 from "../../ctap/protocol/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as conformance$0 from "./conformance/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as credentials$0 from "./credentials/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as failure$0 from "./failure/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as largeblobs$0 from "./largeblobs/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as report$0 from "./report/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as webauthn$0 from "./webauthn/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as uuid$0 from "../../../google/uuid/models.js";

export class AuthenticatorConfigOutput {
    "preview": config$0.AuthenticatorConfigPreview;
    "result": config$0.AuthenticatorConfigResult | null;

    /** Creates a new AuthenticatorConfigOutput instance. */
    constructor($$source: Partial<AuthenticatorConfigOutput> = {}) {
        if (!("preview" in $$source)) {
            this["preview"] = (new config$0.AuthenticatorConfigPreview());
        }
        if (!("result" in $$source)) {
            this["result"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AuthenticatorConfigOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): AuthenticatorConfigOutput {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("preview" in $$parsedSource) {
            $$parsedSource["preview"] = $$createField0_0($$parsedSource["preview"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField1_0($$parsedSource["result"]);
        }
        return new AuthenticatorConfigOutput($$parsedSource as Partial<AuthenticatorConfigOutput>);
    }
}

export class BioEnrollOutput {
    "preview": config$0.BioEnrollPreview;
    "result": config$0.BioEnrollResult | null;

    /** Creates a new BioEnrollOutput instance. */
    constructor($$source: Partial<BioEnrollOutput> = {}) {
        if (!("preview" in $$source)) {
            this["preview"] = (new config$0.BioEnrollPreview());
        }
        if (!("result" in $$source)) {
            this["result"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BioEnrollOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): BioEnrollOutput {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("preview" in $$parsedSource) {
            $$parsedSource["preview"] = $$createField0_0($$parsedSource["preview"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField1_0($$parsedSource["result"]);
        }
        return new BioEnrollOutput($$parsedSource as Partial<BioEnrollOutput>);
    }
}

export class BioListOutput {
    "report": config$0.BioListReport;

    /** Creates a new BioListOutput instance. */
    constructor($$source: Partial<BioListOutput> = {}) {
        if (!("report" in $$source)) {
            this["report"] = (new config$0.BioListReport());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BioListOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): BioListOutput {
        const $$createField0_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("report" in $$parsedSource) {
            $$parsedSource["report"] = $$createField0_0($$parsedSource["report"]);
        }
        return new BioListOutput($$parsedSource as Partial<BioListOutput>);
    }
}

export class BioMutationOutput {
    "preview": config$0.BioMutationPreview;
    "result": config$0.BioMutationResult | null;

    /** Creates a new BioMutationOutput instance. */
    constructor($$source: Partial<BioMutationOutput> = {}) {
        if (!("preview" in $$source)) {
            this["preview"] = (new config$0.BioMutationPreview());
        }
        if (!("result" in $$source)) {
            this["result"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BioMutationOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): BioMutationOutput {
        const $$createField0_0 = $$createType7;
        const $$createField1_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("preview" in $$parsedSource) {
            $$parsedSource["preview"] = $$createField0_0($$parsedSource["preview"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField1_0($$parsedSource["result"]);
        }
        return new BioMutationOutput($$parsedSource as Partial<BioMutationOutput>);
    }
}

export class BioSensorOutput {
    "report": config$0.BioSensorReport;

    /** Creates a new BioSensorOutput instance. */
    constructor($$source: Partial<BioSensorOutput> = {}) {
        if (!("report" in $$source)) {
            this["report"] = (new config$0.BioSensorReport());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BioSensorOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): BioSensorOutput {
        const $$createField0_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("report" in $$parsedSource) {
            $$parsedSource["report"] = $$createField0_0($$parsedSource["report"]);
        }
        return new BioSensorOutput($$parsedSource as Partial<BioSensorOutput>);
    }
}

export class ConfigStatusOutput {
    "report": config$0.StatusReport;

    /** Creates a new ConfigStatusOutput instance. */
    constructor($$source: Partial<ConfigStatusOutput> = {}) {
        if (!("report" in $$source)) {
            this["report"] = (new config$0.StatusReport());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfigStatusOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): ConfigStatusOutput {
        const $$createField0_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("report" in $$parsedSource) {
            $$parsedSource["report"] = $$createField0_0($$parsedSource["report"]);
        }
        return new ConfigStatusOutput($$parsedSource as Partial<ConfigStatusOutput>);
    }
}

export class CredentialDeleteOutput {
    "preview": credentials$0.DeletePreview;
    "result": credentials$0.DeleteResult | null;

    /** Creates a new CredentialDeleteOutput instance. */
    constructor($$source: Partial<CredentialDeleteOutput> = {}) {
        if (!("preview" in $$source)) {
            this["preview"] = (new credentials$0.DeletePreview());
        }
        if (!("result" in $$source)) {
            this["result"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CredentialDeleteOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): CredentialDeleteOutput {
        const $$createField0_0 = $$createType12;
        const $$createField1_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("preview" in $$parsedSource) {
            $$parsedSource["preview"] = $$createField0_0($$parsedSource["preview"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField1_0($$parsedSource["result"]);
        }
        return new CredentialDeleteOutput($$parsedSource as Partial<CredentialDeleteOutput>);
    }
}

export class CredentialUpdateOutput {
    "preview": credentials$0.UpdateUserPreview;
    "result": credentials$0.UpdateUserResult | null;

    /** Creates a new CredentialUpdateOutput instance. */
    constructor($$source: Partial<CredentialUpdateOutput> = {}) {
        if (!("preview" in $$source)) {
            this["preview"] = (new credentials$0.UpdateUserPreview());
        }
        if (!("result" in $$source)) {
            this["result"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CredentialUpdateOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): CredentialUpdateOutput {
        const $$createField0_0 = $$createType15;
        const $$createField1_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("preview" in $$parsedSource) {
            $$parsedSource["preview"] = $$createField0_0($$parsedSource["preview"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField1_0($$parsedSource["result"]);
        }
        return new CredentialUpdateOutput($$parsedSource as Partial<CredentialUpdateOutput>);
    }
}

export class CredentialsOutput {
    "report": credentials$0.InventoryReport;

    /** Creates a new CredentialsOutput instance. */
    constructor($$source: Partial<CredentialsOutput> = {}) {
        if (!("report" in $$source)) {
            this["report"] = (new credentials$0.InventoryReport());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CredentialsOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): CredentialsOutput {
        const $$createField0_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("report" in $$parsedSource) {
            $$parsedSource["report"] = $$createField0_0($$parsedSource["report"]);
        }
        return new CredentialsOutput($$parsedSource as Partial<CredentialsOutput>);
    }
}

export class GetAssertionOutput {
    "preview": webauthn$0.GetAssertionPreview;
    "result": webauthn$0.GetAssertionResult | null;

    /** Creates a new GetAssertionOutput instance. */
    constructor($$source: Partial<GetAssertionOutput> = {}) {
        if (!("preview" in $$source)) {
            this["preview"] = (new webauthn$0.GetAssertionPreview());
        }
        if (!("result" in $$source)) {
            this["result"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetAssertionOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): GetAssertionOutput {
        const $$createField0_0 = $$createType19;
        const $$createField1_0 = $$createType21;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("preview" in $$parsedSource) {
            $$parsedSource["preview"] = $$createField0_0($$parsedSource["preview"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField1_0($$parsedSource["result"]);
        }
        return new GetAssertionOutput($$parsedSource as Partial<GetAssertionOutput>);
    }
}

export class InspectInfo {
    "versions": protocol$0.Versions;
    "extensions"?: extension$0.ExtensionIdentifier[];
    "aaguid": uuid$0.UUID;
    "options"?: { [_ in protocol$0.Option]?: boolean };
    "maxMsgSize"?: number | null;
    "pinUvAuthProtocols"?: protocol$0.PinUvAuthProtocol[];
    "maxCredentialCountInList"?: number | null;
    "maxCredentialIdLength"?: number | null;
    "transports"?: string[];
    "algorithms"?: credential$0.PublicKeyCredentialParameters[];
    "maxSerializedLargeBlobArray"?: number | null;
    "forcePINChange"?: boolean | null;
    "minPINLength"?: number | null;
    "firmwareVersion"?: number | null;
    "maxCredBlobLength"?: number | null;
    "maxRPIDsForSetMinPINLength"?: number | null;
    "preferredPlatformUvAttempts"?: number | null;
    "uvModality"?: protocol$0.UserVerify | null;
    "certifications"?: { [_ in string]?: number };
    "remainingDiscoverableCredentials"?: number | null;
    "vendorPrototypeConfigCommands"?: number[];
    "attestationFormats"?: string[];
    "uvCountSinceLastPinEntry"?: number | null;
    "longTouchForReset"?: boolean | null;
    "encIdentifier"?: string;
    "transportsForReset"?: string[];
    "pinComplexityPolicy"?: boolean | null;
    "pinComplexityPolicyURL"?: string | null;
    "maxPINLength"?: number | null;
    "encCredStoreState"?: string;
    "authenticatorConfigCommands"?: number[];
    "uvModalityLabel"?: string;
    "conformance": conformance$0.Report;

    /** Creates a new InspectInfo instance. */
    constructor($$source: Partial<InspectInfo> = {}) {
        if (!("versions" in $$source)) {
            this["versions"] = [];
        }
        if (!("aaguid" in $$source)) {
            this["aaguid"] = "";
        }
        if (!("conformance" in $$source)) {
            this["conformance"] = (new conformance$0.Report());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InspectInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): InspectInfo {
        const $$createField0_0 = $$createType22;
        const $$createField1_0 = $$createType24;
        const $$createField3_0 = $$createType25;
        const $$createField5_0 = $$createType26;
        const $$createField8_0 = $$createType27;
        const $$createField9_0 = $$createType29;
        const $$createField18_0 = $$createType30;
        const $$createField20_0 = $$createType31;
        const $$createField21_0 = $$createType27;
        const $$createField24_0 = $Create.ByteSlice;
        const $$createField25_0 = $$createType27;
        const $$createField29_0 = $Create.ByteSlice;
        const $$createField30_0 = $$createType31;
        const $$createField32_0 = $$createType32;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("versions" in $$parsedSource) {
            $$parsedSource["versions"] = $$createField0_0($$parsedSource["versions"]);
        }
        if ("extensions" in $$parsedSource) {
            $$parsedSource["extensions"] = $$createField1_0($$parsedSource["extensions"]);
        }
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField3_0($$parsedSource["options"]);
        }
        if ("pinUvAuthProtocols" in $$parsedSource) {
            $$parsedSource["pinUvAuthProtocols"] = $$createField5_0($$parsedSource["pinUvAuthProtocols"]);
        }
        if ("transports" in $$parsedSource) {
            $$parsedSource["transports"] = $$createField8_0($$parsedSource["transports"]);
        }
        if ("algorithms" in $$parsedSource) {
            $$parsedSource["algorithms"] = $$createField9_0($$parsedSource["algorithms"]);
        }
        if ("certifications" in $$parsedSource) {
            $$parsedSource["certifications"] = $$createField18_0($$parsedSource["certifications"]);
        }
        if ("vendorPrototypeConfigCommands" in $$parsedSource) {
            $$parsedSource["vendorPrototypeConfigCommands"] = $$createField20_0($$parsedSource["vendorPrototypeConfigCommands"]);
        }
        if ("attestationFormats" in $$parsedSource) {
            $$parsedSource["attestationFormats"] = $$createField21_0($$parsedSource["attestationFormats"]);
        }
        if ("encIdentifier" in $$parsedSource) {
            $$parsedSource["encIdentifier"] = $$createField24_0($$parsedSource["encIdentifier"]);
        }
        if ("transportsForReset" in $$parsedSource) {
            $$parsedSource["transportsForReset"] = $$createField25_0($$parsedSource["transportsForReset"]);
        }
        if ("encCredStoreState" in $$parsedSource) {
            $$parsedSource["encCredStoreState"] = $$createField29_0($$parsedSource["encCredStoreState"]);
        }
        if ("authenticatorConfigCommands" in $$parsedSource) {
            $$parsedSource["authenticatorConfigCommands"] = $$createField30_0($$parsedSource["authenticatorConfigCommands"]);
        }
        if ("conformance" in $$parsedSource) {
            $$parsedSource["conformance"] = $$createField32_0($$parsedSource["conformance"]);
        }
        return new InspectInfo($$parsedSource as Partial<InspectInfo>);
    }
}

export class InspectOutput {
    "result": InspectResult;

    /** Creates a new InspectOutput instance. */
    constructor($$source: Partial<InspectOutput> = {}) {
        if (!("result" in $$source)) {
            this["result"] = (new InspectResult());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InspectOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): InspectOutput {
        const $$createField0_0 = $$createType33;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField0_0($$parsedSource["result"]);
        }
        return new InspectOutput($$parsedSource as Partial<InspectOutput>);
    }
}

export class InspectResult {
    "device": report$0.DeviceReport;
    "info": InspectInfo;

    /** Creates a new InspectResult instance. */
    constructor($$source: Partial<InspectResult> = {}) {
        if (!("device" in $$source)) {
            this["device"] = (new report$0.DeviceReport());
        }
        if (!("info" in $$source)) {
            this["info"] = (new InspectInfo());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InspectResult instance from a string or object.
     */
    static createFrom($$source: any = {}): InspectResult {
        const $$createField0_0 = $$createType34;
        const $$createField1_0 = $$createType35;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("device" in $$parsedSource) {
            $$parsedSource["device"] = $$createField0_0($$parsedSource["device"]);
        }
        if ("info" in $$parsedSource) {
            $$parsedSource["info"] = $$createField1_0($$parsedSource["info"]);
        }
        return new InspectResult($$parsedSource as Partial<InspectResult>);
    }
}

export enum InteractionKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    InteractionKindPIN = "pin",
    InteractionKindUserVerification = "user-verification",
    InteractionKindTouch = "touch",
    InteractionKindConfirm = "confirm",
};

export class InteractionRequest {
    "kind": InteractionKind;
    "message"?: string;
    "permission"?: string;
    "destructive"?: boolean;
    "preview"?: any;
    "pinState"?: PINInteractionState | null;

    /** Creates a new InteractionRequest instance. */
    constructor($$source: Partial<InteractionRequest> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = InteractionKind.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InteractionRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): InteractionRequest {
        const $$createField5_0 = $$createType37;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("pinState" in $$parsedSource) {
            $$parsedSource["pinState"] = $$createField5_0($$parsedSource["pinState"]);
        }
        return new InteractionRequest($$parsedSource as Partial<InteractionRequest>);
    }
}

export class LargeBlobListOutput {
    "report": largeblobs$0.ListReport;

    /** Creates a new LargeBlobListOutput instance. */
    constructor($$source: Partial<LargeBlobListOutput> = {}) {
        if (!("report" in $$source)) {
            this["report"] = (new largeblobs$0.ListReport());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LargeBlobListOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): LargeBlobListOutput {
        const $$createField0_0 = $$createType38;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("report" in $$parsedSource) {
            $$parsedSource["report"] = $$createField0_0($$parsedSource["report"]);
        }
        return new LargeBlobListOutput($$parsedSource as Partial<LargeBlobListOutput>);
    }
}

export class LargeBlobMutationOutput {
    "preview": largeblobs$0.MutationPreview;
    "result": largeblobs$0.MutationResult | null;

    /** Creates a new LargeBlobMutationOutput instance. */
    constructor($$source: Partial<LargeBlobMutationOutput> = {}) {
        if (!("preview" in $$source)) {
            this["preview"] = (new largeblobs$0.MutationPreview());
        }
        if (!("result" in $$source)) {
            this["result"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LargeBlobMutationOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): LargeBlobMutationOutput {
        const $$createField0_0 = $$createType39;
        const $$createField1_0 = $$createType41;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("preview" in $$parsedSource) {
            $$parsedSource["preview"] = $$createField0_0($$parsedSource["preview"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField1_0($$parsedSource["result"]);
        }
        return new LargeBlobMutationOutput($$parsedSource as Partial<LargeBlobMutationOutput>);
    }
}

export class LargeBlobReadOutput {
    "report": largeblobs$0.ReadReport;

    /** Creates a new LargeBlobReadOutput instance. */
    constructor($$source: Partial<LargeBlobReadOutput> = {}) {
        if (!("report" in $$source)) {
            this["report"] = (new largeblobs$0.ReadReport());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LargeBlobReadOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): LargeBlobReadOutput {
        const $$createField0_0 = $$createType42;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("report" in $$parsedSource) {
            $$parsedSource["report"] = $$createField0_0($$parsedSource["report"]);
        }
        return new LargeBlobReadOutput($$parsedSource as Partial<LargeBlobReadOutput>);
    }
}

export enum LogCode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    LogCodeDiscoveryRun = "discovery.run",
    LogCodeDiscoveryChanged = "discovery.changed",
    LogCodeMDSLookup = "mds.lookup",
    LogCodeSessionOpen = "session.open",
    LogCodeSessionClose = "session.close",
    LogCodeOperationRun = "operation.run",
    LogCodeOperationProgress = "operation.progress",
    LogCodeInteractionRequest = "interaction.request",
    LogCodeInteractionResolve = "interaction.resolve",
    LogCodeCTAPCommand = "ctap.command",
};

export class LogEntry {
    "timestamp": string;
    "durationMilliseconds"?: number;
    "layer": LogLayer;
    "level": LogLevel;
    "outcome": LogOutcome;
    "code": LogCode;
    "params"?: { [_ in string]?: string };
    "operationKind"?: OperationKind;
    "command"?: string;
    "commandCode"?: number;
    "subCommandFamily"?: string;
    "subCommand"?: string;
    "subCommandCode"?: number | null;
    "request"?: LogPayload | null;
    "response"?: LogPayload | null;
    "error"?: failure$0.Failure | null;
    "errorMessage"?: string;
    "redactedFields"?: string[];
    "sessionId"?: string;
    "operationId"?: string;

    /** Creates a new LogEntry instance. */
    constructor($$source: Partial<LogEntry> = {}) {
        if (!("timestamp" in $$source)) {
            this["timestamp"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("layer" in $$source)) {
            this["layer"] = LogLayer.$zero;
        }
        if (!("level" in $$source)) {
            this["level"] = LogLevel.$zero;
        }
        if (!("outcome" in $$source)) {
            this["outcome"] = LogOutcome.$zero;
        }
        if (!("code" in $$source)) {
            this["code"] = LogCode.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): LogEntry {
        const $$createField6_0 = $$createType43;
        const $$createField13_0 = $$createType45;
        const $$createField14_0 = $$createType45;
        const $$createField15_0 = $$createType47;
        const $$createField17_0 = $$createType27;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("params" in $$parsedSource) {
            $$parsedSource["params"] = $$createField6_0($$parsedSource["params"]);
        }
        if ("request" in $$parsedSource) {
            $$parsedSource["request"] = $$createField13_0($$parsedSource["request"]);
        }
        if ("response" in $$parsedSource) {
            $$parsedSource["response"] = $$createField14_0($$parsedSource["response"]);
        }
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField15_0($$parsedSource["error"]);
        }
        if ("redactedFields" in $$parsedSource) {
            $$parsedSource["redactedFields"] = $$createField17_0($$parsedSource["redactedFields"]);
        }
        return new LogEntry($$parsedSource as Partial<LogEntry>);
    }
}

export class LogJournalBatch {
    "entries": LogJournalRecord[];
    "cursor": number;
    "truncated"?: boolean;

    /** Creates a new LogJournalBatch instance. */
    constructor($$source: Partial<LogJournalBatch> = {}) {
        if (!("entries" in $$source)) {
            this["entries"] = [];
        }
        if (!("cursor" in $$source)) {
            this["cursor"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogJournalBatch instance from a string or object.
     */
    static createFrom($$source: any = {}): LogJournalBatch {
        const $$createField0_0 = $$createType49;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField0_0($$parsedSource["entries"]);
        }
        return new LogJournalBatch($$parsedSource as Partial<LogJournalBatch>);
    }
}

export class LogJournalRecord {
    "sequence": number;
    "entry": LogEntry;

    /** Creates a new LogJournalRecord instance. */
    constructor($$source: Partial<LogJournalRecord> = {}) {
        if (!("sequence" in $$source)) {
            this["sequence"] = 0;
        }
        if (!("entry" in $$source)) {
            this["entry"] = (new LogEntry());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogJournalRecord instance from a string or object.
     */
    static createFrom($$source: any = {}): LogJournalRecord {
        const $$createField1_0 = $$createType50;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entry" in $$parsedSource) {
            $$parsedSource["entry"] = $$createField1_0($$parsedSource["entry"]);
        }
        return new LogJournalRecord($$parsedSource as Partial<LogJournalRecord>);
    }
}

export enum LogLayer {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    LogLayerService = "service",
    LogLayerSession = "session",
    LogLayerOperation = "operation",
    LogLayerInteraction = "interaction",
    LogLayerCTAP = "ctap",
};

export enum LogLevel {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    LogLevelDebug = "debug",
    LogLevelInfo = "info",
    LogLevelWarning = "warning",
    LogLevelError = "error",
};

export enum LogOutcome {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    LogOutcomeEvent = "event",
    LogOutcomeSucceeded = "succeeded",
    LogOutcomeFailed = "failed",
    LogOutcomeCanceled = "canceled",
};

export class LogPayload {
    "json": string;
    "originalBytes": number;
    "storedBytes": number;
    "truncated": boolean;

    /** Creates a new LogPayload instance. */
    constructor($$source: Partial<LogPayload> = {}) {
        if (!("json" in $$source)) {
            this["json"] = "";
        }
        if (!("originalBytes" in $$source)) {
            this["originalBytes"] = 0;
        }
        if (!("storedBytes" in $$source)) {
            this["storedBytes"] = 0;
        }
        if (!("truncated" in $$source)) {
            this["truncated"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): LogPayload {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogPayload($$parsedSource as Partial<LogPayload>);
    }
}

export class MakeCredentialOutput {
    "preview": webauthn$0.MakeCredentialPreview;
    "result": webauthn$0.MakeCredentialResult | null;

    /** Creates a new MakeCredentialOutput instance. */
    constructor($$source: Partial<MakeCredentialOutput> = {}) {
        if (!("preview" in $$source)) {
            this["preview"] = (new webauthn$0.MakeCredentialPreview());
        }
        if (!("result" in $$source)) {
            this["result"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MakeCredentialOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): MakeCredentialOutput {
        const $$createField0_0 = $$createType51;
        const $$createField1_0 = $$createType53;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("preview" in $$parsedSource) {
            $$parsedSource["preview"] = $$createField0_0($$parsedSource["preview"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField1_0($$parsedSource["result"]);
        }
        return new MakeCredentialOutput($$parsedSource as Partial<MakeCredentialOutput>);
    }
}

export class OperationEvent {
    "stage": OperationStage;
    "kind"?: InteractionKind;
    "message"?: string;
    "completed"?: number | null;
    "total"?: number | null;
    "sampleStatus"?: string;

    /** Creates a new OperationEvent instance. */
    constructor($$source: Partial<OperationEvent> = {}) {
        if (!("stage" in $$source)) {
            this["stage"] = OperationStage.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OperationEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): OperationEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OperationEvent($$parsedSource as Partial<OperationEvent>);
    }
}

export enum OperationKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    OperationInspect = "inspect",
    OperationListCredentials = "credentials.list",
    OperationDeleteCredential = "credentials.delete",
    OperationUpdateCredentialUser = "credentials.updateUser",
    OperationReadLargeBlob = "largeBlobs.read",
    OperationListLargeBlobs = "largeBlobs.list",
    OperationWriteLargeBlob = "largeBlobs.write",
    OperationDeleteLargeBlob = "largeBlobs.delete",
    OperationGarbageCollectLargeBlobs = "largeBlobs.garbageCollect",
    OperationConfigStatus = "config.status",
    OperationBioSensorInfo = "config.bio.sensorInfo",
    OperationBioList = "config.bio.list",
    OperationBioEnroll = "config.bio.enroll",
    OperationBioRename = "config.bio.rename",
    OperationBioRemove = "config.bio.remove",
    OperationResetFactory = "config.reset.factory",
    OperationSetPIN = "config.pin.set",
    OperationChangePIN = "config.pin.change",
    OperationSetAlwaysUV = "config.alwaysUv.set",
    OperationSetMinPINLength = "config.minPinLength.set",
    OperationMakeCredential = "webauthn.makeCredential",
    OperationGetAssertion = "webauthn.getAssertion",
};

export enum OperationStage {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    OperationStageInteractionRequired = "interaction-required",
    OperationStageEnumeratingRPs = "enumerating-rps",
    OperationStageEnumeratingCredentials = "enumerating-credentials",
    OperationStageCapturingBioSample = "capturing-bio-sample",
};

export class PINInteractionState {
    "failure"?: failure$0.Failure | null;
    "retriesRemaining"?: number | null;
    "powerCycleState"?: boolean | null;

    /** Creates a new PINInteractionState instance. */
    constructor($$source: Partial<PINInteractionState> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PINInteractionState instance from a string or object.
     */
    static createFrom($$source: any = {}): PINInteractionState {
        const $$createField0_0 = $$createType47;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("failure" in $$parsedSource) {
            $$parsedSource["failure"] = $$createField0_0($$parsedSource["failure"]);
        }
        return new PINInteractionState($$parsedSource as Partial<PINInteractionState>);
    }
}

export class PINOutput {
    "preview": config$0.PINMutationPreview;
    "result": config$0.PINMutationResult | null;

    /** Creates a new PINOutput instance. */
    constructor($$source: Partial<PINOutput> = {}) {
        if (!("preview" in $$source)) {
            this["preview"] = (new config$0.PINMutationPreview());
        }
        if (!("result" in $$source)) {
            this["result"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PINOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): PINOutput {
        const $$createField0_0 = $$createType54;
        const $$createField1_0 = $$createType56;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("preview" in $$parsedSource) {
            $$parsedSource["preview"] = $$createField0_0($$parsedSource["preview"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField1_0($$parsedSource["result"]);
        }
        return new PINOutput($$parsedSource as Partial<PINOutput>);
    }
}

export class ResetFactoryOutput {
    "preview": config$0.ResetPreview;
    "result": config$0.ResetResult | null;

    /** Creates a new ResetFactoryOutput instance. */
    constructor($$source: Partial<ResetFactoryOutput> = {}) {
        if (!("preview" in $$source)) {
            this["preview"] = (new config$0.ResetPreview());
        }
        if (!("result" in $$source)) {
            this["result"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResetFactoryOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): ResetFactoryOutput {
        const $$createField0_0 = $$createType57;
        const $$createField1_0 = $$createType59;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("preview" in $$parsedSource) {
            $$parsedSource["preview"] = $$createField0_0($$parsedSource["preview"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField1_0($$parsedSource["result"]);
        }
        return new ResetFactoryOutput($$parsedSource as Partial<ResetFactoryOutput>);
    }
}

export class SessionInfo {
    "device": report$0.DeviceReport;
    "closed": boolean;

    /** Creates a new SessionInfo instance. */
    constructor($$source: Partial<SessionInfo> = {}) {
        if (!("device" in $$source)) {
            this["device"] = (new report$0.DeviceReport());
        }
        if (!("closed" in $$source)) {
            this["closed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionInfo {
        const $$createField0_0 = $$createType34;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("device" in $$parsedSource) {
            $$parsedSource["device"] = $$createField0_0($$parsedSource["device"]);
        }
        return new SessionInfo($$parsedSource as Partial<SessionInfo>);
    }
}

export enum VerificationFlow {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    VerificationFlowDefault = "",
    VerificationFlowPIN = "pin",
};

// Private type creation functions
const $$createType0 = config$0.AuthenticatorConfigPreview.createFrom;
const $$createType1 = config$0.AuthenticatorConfigResult.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = config$0.BioEnrollPreview.createFrom;
const $$createType4 = config$0.BioEnrollResult.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = config$0.BioListReport.createFrom;
const $$createType7 = config$0.BioMutationPreview.createFrom;
const $$createType8 = config$0.BioMutationResult.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = config$0.BioSensorReport.createFrom;
const $$createType11 = config$0.StatusReport.createFrom;
const $$createType12 = credentials$0.DeletePreview.createFrom;
const $$createType13 = credentials$0.DeleteResult.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = credentials$0.UpdateUserPreview.createFrom;
const $$createType16 = credentials$0.UpdateUserResult.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = credentials$0.InventoryReport.createFrom;
const $$createType19 = webauthn$0.GetAssertionPreview.createFrom;
const $$createType20 = webauthn$0.GetAssertionResult.createFrom;
const $$createType21 = $Create.Nullable($$createType20);
var $$createType22 = (function $$initCreateType22(...args: any[]): any {
    if ($$createType22 === $$initCreateType22) {
        $$createType22 = $$createType23;
    }
    return $$createType22(...args);
});
const $$createType23 = $Create.Array($Create.Any);
const $$createType24 = $Create.Array($Create.Any);
const $$createType25 = $Create.Map($Create.Any, $Create.Any);
const $$createType26 = $Create.Array($Create.Any);
const $$createType27 = $Create.Array($Create.Any);
const $$createType28 = credential$0.PublicKeyCredentialParameters.createFrom;
const $$createType29 = $Create.Array($$createType28);
const $$createType30 = $Create.Map($Create.Any, $Create.Any);
const $$createType31 = $Create.Array($Create.Any);
const $$createType32 = conformance$0.Report.createFrom;
const $$createType33 = InspectResult.createFrom;
const $$createType34 = report$0.DeviceReport.createFrom;
const $$createType35 = InspectInfo.createFrom;
const $$createType36 = PINInteractionState.createFrom;
const $$createType37 = $Create.Nullable($$createType36);
const $$createType38 = largeblobs$0.ListReport.createFrom;
const $$createType39 = largeblobs$0.MutationPreview.createFrom;
const $$createType40 = largeblobs$0.MutationResult.createFrom;
const $$createType41 = $Create.Nullable($$createType40);
const $$createType42 = largeblobs$0.ReadReport.createFrom;
const $$createType43 = $Create.Map($Create.Any, $Create.Any);
const $$createType44 = LogPayload.createFrom;
const $$createType45 = $Create.Nullable($$createType44);
const $$createType46 = failure$0.Failure.createFrom;
const $$createType47 = $Create.Nullable($$createType46);
const $$createType48 = LogJournalRecord.createFrom;
const $$createType49 = $Create.Array($$createType48);
const $$createType50 = LogEntry.createFrom;
const $$createType51 = webauthn$0.MakeCredentialPreview.createFrom;
const $$createType52 = webauthn$0.MakeCredentialResult.createFrom;
const $$createType53 = $Create.Nullable($$createType52);
const $$createType54 = config$0.PINMutationPreview.createFrom;
const $$createType55 = config$0.PINMutationResult.createFrom;
const $$createType56 = $Create.Nullable($$createType55);
const $$createType57 = config$0.ResetPreview.createFrom;
const $$createType58 = config$0.ResetResult.createFrom;
const $$createType59 = $Create.Nullable($$createType58);
