// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as transport$0 from "../../transport/models.js";

/**
 * AttachmentID identifies one currently reachable transport endpoint. It is
 * not a physical-device identity and is never derived from hardware identity.
 */
export type AttachmentID = string;

/**
 * AttachmentReport is the transport-layer view of one reachable CTAP
 * authenticator.
 */
export class AttachmentReport {
    "id": AttachmentID;
    "transport": transport$0.Mode;
    "usb"?: USBReport | null;
    "smartCard"?: SmartCardReport | null;

    /** Creates a new AttachmentReport instance. */
    constructor($$source: Partial<AttachmentReport> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("transport" in $$source)) {
            this["transport"] = transport$0.Mode.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AttachmentReport instance from a string or object.
     */
    static createFrom($$source: any = {}): AttachmentReport {
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("usb" in $$parsedSource) {
            $$parsedSource["usb"] = $$createField2_0($$parsedSource["usb"]);
        }
        if ("smartCard" in $$parsedSource) {
            $$parsedSource["smartCard"] = $$createField3_0($$parsedSource["smartCard"]);
        }
        return new AttachmentReport($$parsedSource as Partial<AttachmentReport>);
    }
}

/**
 * DeviceReport describes one selectable transport attachment.
 */
export class DeviceReport {
    "attachment": AttachmentReport;

    /** Creates a new DeviceReport instance. */
    constructor($$source: Partial<DeviceReport> = {}) {
        if (!("attachment" in $$source)) {
            this["attachment"] = (new AttachmentReport());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceReport instance from a string or object.
     */
    static createFrom($$source: any = {}): DeviceReport {
        const $$createField0_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("attachment" in $$parsedSource) {
            $$parsedSource["attachment"] = $$createField0_0($$parsedSource["attachment"]);
        }
        return new DeviceReport($$parsedSource as Partial<DeviceReport>);
    }
}

/**
 * SmartCardReport describes a PC/SC attachment separately from card identity.
 */
export class SmartCardReport {
    "reader": string;
    "atr"?: string;
    "interface": transport$0.SmartCardInterface;

    /** Creates a new SmartCardReport instance. */
    constructor($$source: Partial<SmartCardReport> = {}) {
        if (!("reader" in $$source)) {
            this["reader"] = "";
        }
        if (!("interface" in $$source)) {
            this["interface"] = transport$0.SmartCardInterface.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SmartCardReport instance from a string or object.
     */
    static createFrom($$source: any = {}): SmartCardReport {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SmartCardReport($$parsedSource as Partial<SmartCardReport>);
    }
}

/**
 * USBReport contains observations reported by USB/HID topology. ReportedSerial
 * is not the canonical hardware serial returned by a vendor provider.
 */
export class USBReport {
    "manufacturer"?: string;
    "product"?: string;
    "reportedSerial"?: string;
    "vendorId": number;
    "productId": number;

    /** Creates a new USBReport instance. */
    constructor($$source: Partial<USBReport> = {}) {
        if (!("vendorId" in $$source)) {
            this["vendorId"] = 0;
        }
        if (!("productId" in $$source)) {
            this["productId"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new USBReport instance from a string or object.
     */
    static createFrom($$source: any = {}): USBReport {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new USBReport($$parsedSource as Partial<USBReport>);
    }
}

// Private type creation functions
const $$createType0 = USBReport.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = SmartCardReport.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = AttachmentReport.createFrom;
