// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as attestation$0 from "../../ctap/attestation/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as credential$0 from "../../ctap/credential/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as webauthn$1 from "../../ctap/webauthn/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../model/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as failure$0 from "../model/failure/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as largeblobs$0 from "../model/largeblobs/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mds$0 from "../model/mds/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as report$0 from "../model/report/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as webauthn$0 from "../model/webauthn/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as transport$0 from "../transport/models.js";

export class ActiveSelection {
    "id": SelectionID;

    /** Creates a new ActiveSelection instance. */
    constructor($$source: Partial<ActiveSelection> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActiveSelection instance from a string or object.
     */
    static createFrom($$source: any = {}): ActiveSelection {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ActiveSelection($$parsedSource as Partial<ActiveSelection>);
    }
}

export class AlwaysUVRequest {
    "selectionId": SelectionID;
    "verificationFlow"?: model$0.VerificationFlow;
    "target": config$0.AlwaysUVTarget;
    "confirmed"?: boolean;
    "confirmationMessage"?: string;
    "dryRun"?: boolean;

    /** Creates a new AlwaysUVRequest instance. */
    constructor($$source: Partial<AlwaysUVRequest> = {}) {
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }
        if (!("target" in $$source)) {
            this["target"] = config$0.AlwaysUVTarget.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AlwaysUVRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): AlwaysUVRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AlwaysUVRequest($$parsedSource as Partial<AlwaysUVRequest>);
    }
}

export class AuthenticatorConfigEnvelope {
    "operationId": OperationID;
    "selectionId": SelectionID;
    "kind": model$0.OperationKind;
    "authenticatorClosed": boolean;
    "error"?: failure$0.Failure | null;
    "result"?: model$0.AuthenticatorConfigOutput | null;

    /** Creates a new AuthenticatorConfigEnvelope instance. */
    constructor($$source: Partial<AuthenticatorConfigEnvelope> = {}) {
        if (!("operationId" in $$source)) {
            this["operationId"] = "";
        }
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = model$0.OperationKind.$zero;
        }
        if (!("authenticatorClosed" in $$source)) {
            this["authenticatorClosed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AuthenticatorConfigEnvelope instance from a string or object.
     */
    static createFrom($$source: any = {}): AuthenticatorConfigEnvelope {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField4_0($$parsedSource["error"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField5_0($$parsedSource["result"]);
        }
        return new AuthenticatorConfigEnvelope($$parsedSource as Partial<AuthenticatorConfigEnvelope>);
    }
}

export class BioEnrollEnvelope {
    "operationId": OperationID;
    "selectionId": SelectionID;
    "kind": model$0.OperationKind;
    "authenticatorClosed": boolean;
    "error"?: failure$0.Failure | null;
    "result"?: model$0.BioEnrollOutput | null;

    /** Creates a new BioEnrollEnvelope instance. */
    constructor($$source: Partial<BioEnrollEnvelope> = {}) {
        if (!("operationId" in $$source)) {
            this["operationId"] = "";
        }
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = model$0.OperationKind.$zero;
        }
        if (!("authenticatorClosed" in $$source)) {
            this["authenticatorClosed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BioEnrollEnvelope instance from a string or object.
     */
    static createFrom($$source: any = {}): BioEnrollEnvelope {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField4_0($$parsedSource["error"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField5_0($$parsedSource["result"]);
        }
        return new BioEnrollEnvelope($$parsedSource as Partial<BioEnrollEnvelope>);
    }
}

export class BioEnrollRequest {
    "selectionId": SelectionID;
    "verificationFlow"?: model$0.VerificationFlow;
    "timeoutMilliseconds"?: number;
    "confirmed"?: boolean;
    "confirmationMessage"?: string;
    "dryRun"?: boolean;

    /** Creates a new BioEnrollRequest instance. */
    constructor($$source: Partial<BioEnrollRequest> = {}) {
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BioEnrollRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): BioEnrollRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BioEnrollRequest($$parsedSource as Partial<BioEnrollRequest>);
    }
}

export class BioListEnvelope {
    "operationId": OperationID;
    "selectionId": SelectionID;
    "kind": model$0.OperationKind;
    "authenticatorClosed": boolean;
    "error"?: failure$0.Failure | null;
    "result"?: model$0.BioListOutput | null;

    /** Creates a new BioListEnvelope instance. */
    constructor($$source: Partial<BioListEnvelope> = {}) {
        if (!("operationId" in $$source)) {
            this["operationId"] = "";
        }
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = model$0.OperationKind.$zero;
        }
        if (!("authenticatorClosed" in $$source)) {
            this["authenticatorClosed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BioListEnvelope instance from a string or object.
     */
    static createFrom($$source: any = {}): BioListEnvelope {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField4_0($$parsedSource["error"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField5_0($$parsedSource["result"]);
        }
        return new BioListEnvelope($$parsedSource as Partial<BioListEnvelope>);
    }
}

export class BioMutationEnvelope {
    "operationId": OperationID;
    "selectionId": SelectionID;
    "kind": model$0.OperationKind;
    "authenticatorClosed": boolean;
    "error"?: failure$0.Failure | null;
    "result"?: model$0.BioMutationOutput | null;

    /** Creates a new BioMutationEnvelope instance. */
    constructor($$source: Partial<BioMutationEnvelope> = {}) {
        if (!("operationId" in $$source)) {
            this["operationId"] = "";
        }
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = model$0.OperationKind.$zero;
        }
        if (!("authenticatorClosed" in $$source)) {
            this["authenticatorClosed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BioMutationEnvelope instance from a string or object.
     */
    static createFrom($$source: any = {}): BioMutationEnvelope {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField4_0($$parsedSource["error"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField5_0($$parsedSource["result"]);
        }
        return new BioMutationEnvelope($$parsedSource as Partial<BioMutationEnvelope>);
    }
}

export class BioRemoveRequest {
    "selectionId": SelectionID;
    "verificationFlow"?: model$0.VerificationFlow;
    "templateIdHex": string;
    "confirmed"?: boolean;
    "confirmationMessage"?: string;
    "dryRun"?: boolean;

    /** Creates a new BioRemoveRequest instance. */
    constructor($$source: Partial<BioRemoveRequest> = {}) {
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }
        if (!("templateIdHex" in $$source)) {
            this["templateIdHex"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BioRemoveRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): BioRemoveRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BioRemoveRequest($$parsedSource as Partial<BioRemoveRequest>);
    }
}

export class BioRenameRequest {
    "selectionId": SelectionID;
    "verificationFlow"?: model$0.VerificationFlow;
    "templateIdHex": string;
    "friendlyName": string;
    "confirmed"?: boolean;
    "confirmationMessage"?: string;
    "dryRun"?: boolean;

    /** Creates a new BioRenameRequest instance. */
    constructor($$source: Partial<BioRenameRequest> = {}) {
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }
        if (!("templateIdHex" in $$source)) {
            this["templateIdHex"] = "";
        }
        if (!("friendlyName" in $$source)) {
            this["friendlyName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BioRenameRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): BioRenameRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BioRenameRequest($$parsedSource as Partial<BioRenameRequest>);
    }
}

export class BioSensorEnvelope {
    "operationId": OperationID;
    "selectionId": SelectionID;
    "kind": model$0.OperationKind;
    "authenticatorClosed": boolean;
    "error"?: failure$0.Failure | null;
    "result"?: model$0.BioSensorOutput | null;

    /** Creates a new BioSensorEnvelope instance. */
    constructor($$source: Partial<BioSensorEnvelope> = {}) {
        if (!("operationId" in $$source)) {
            this["operationId"] = "";
        }
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = model$0.OperationKind.$zero;
        }
        if (!("authenticatorClosed" in $$source)) {
            this["authenticatorClosed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BioSensorEnvelope instance from a string or object.
     */
    static createFrom($$source: any = {}): BioSensorEnvelope {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField4_0($$parsedSource["error"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField5_0($$parsedSource["result"]);
        }
        return new BioSensorEnvelope($$parsedSource as Partial<BioSensorEnvelope>);
    }
}

export class CancelOperationRequest {
    "operationId": OperationID;

    /** Creates a new CancelOperationRequest instance. */
    constructor($$source: Partial<CancelOperationRequest> = {}) {
        if (!("operationId" in $$source)) {
            this["operationId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CancelOperationRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CancelOperationRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CancelOperationRequest($$parsedSource as Partial<CancelOperationRequest>);
    }
}

export class ConfigStatusEnvelope {
    "operationId": OperationID;
    "selectionId": SelectionID;
    "kind": model$0.OperationKind;
    "authenticatorClosed": boolean;
    "error"?: failure$0.Failure | null;
    "result"?: model$0.ConfigStatusOutput | null;

    /** Creates a new ConfigStatusEnvelope instance. */
    constructor($$source: Partial<ConfigStatusEnvelope> = {}) {
        if (!("operationId" in $$source)) {
            this["operationId"] = "";
        }
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = model$0.OperationKind.$zero;
        }
        if (!("authenticatorClosed" in $$source)) {
            this["authenticatorClosed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfigStatusEnvelope instance from a string or object.
     */
    static createFrom($$source: any = {}): ConfigStatusEnvelope {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField4_0($$parsedSource["error"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField5_0($$parsedSource["result"]);
        }
        return new ConfigStatusEnvelope($$parsedSource as Partial<ConfigStatusEnvelope>);
    }
}

export class CredentialDeleteEnvelope {
    "operationId": OperationID;
    "selectionId": SelectionID;
    "kind": model$0.OperationKind;
    "authenticatorClosed": boolean;
    "error"?: failure$0.Failure | null;
    "result"?: model$0.CredentialDeleteOutput | null;

    /** Creates a new CredentialDeleteEnvelope instance. */
    constructor($$source: Partial<CredentialDeleteEnvelope> = {}) {
        if (!("operationId" in $$source)) {
            this["operationId"] = "";
        }
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = model$0.OperationKind.$zero;
        }
        if (!("authenticatorClosed" in $$source)) {
            this["authenticatorClosed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CredentialDeleteEnvelope instance from a string or object.
     */
    static createFrom($$source: any = {}): CredentialDeleteEnvelope {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField4_0($$parsedSource["error"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField5_0($$parsedSource["result"]);
        }
        return new CredentialDeleteEnvelope($$parsedSource as Partial<CredentialDeleteEnvelope>);
    }
}

export class CredentialDeleteRequest {
    "selectionId": SelectionID;
    "verificationFlow"?: model$0.VerificationFlow;
    "credentialIdHex": string;
    "confirmed"?: boolean;
    "confirmationMessage"?: string;
    "dryRun"?: boolean;

    /** Creates a new CredentialDeleteRequest instance. */
    constructor($$source: Partial<CredentialDeleteRequest> = {}) {
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }
        if (!("credentialIdHex" in $$source)) {
            this["credentialIdHex"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CredentialDeleteRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CredentialDeleteRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CredentialDeleteRequest($$parsedSource as Partial<CredentialDeleteRequest>);
    }
}

export class CredentialListRequest {
    "selectionId": SelectionID;
    "verificationFlow"?: model$0.VerificationFlow;

    /** Creates a new CredentialListRequest instance. */
    constructor($$source: Partial<CredentialListRequest> = {}) {
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CredentialListRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CredentialListRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CredentialListRequest($$parsedSource as Partial<CredentialListRequest>);
    }
}

export class CredentialStoreStateEnvelope {
    "operationId": OperationID;
    "selectionId": SelectionID;
    "kind": model$0.OperationKind;
    "authenticatorClosed": boolean;
    "error"?: failure$0.Failure | null;
    "result"?: model$0.CredentialStoreStateOutput | null;

    /** Creates a new CredentialStoreStateEnvelope instance. */
    constructor($$source: Partial<CredentialStoreStateEnvelope> = {}) {
        if (!("operationId" in $$source)) {
            this["operationId"] = "";
        }
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = model$0.OperationKind.$zero;
        }
        if (!("authenticatorClosed" in $$source)) {
            this["authenticatorClosed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CredentialStoreStateEnvelope instance from a string or object.
     */
    static createFrom($$source: any = {}): CredentialStoreStateEnvelope {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField4_0($$parsedSource["error"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField5_0($$parsedSource["result"]);
        }
        return new CredentialStoreStateEnvelope($$parsedSource as Partial<CredentialStoreStateEnvelope>);
    }
}

export class CredentialUpdateEnvelope {
    "operationId": OperationID;
    "selectionId": SelectionID;
    "kind": model$0.OperationKind;
    "authenticatorClosed": boolean;
    "error"?: failure$0.Failure | null;
    "result"?: model$0.CredentialUpdateOutput | null;

    /** Creates a new CredentialUpdateEnvelope instance. */
    constructor($$source: Partial<CredentialUpdateEnvelope> = {}) {
        if (!("operationId" in $$source)) {
            this["operationId"] = "";
        }
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = model$0.OperationKind.$zero;
        }
        if (!("authenticatorClosed" in $$source)) {
            this["authenticatorClosed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CredentialUpdateEnvelope instance from a string or object.
     */
    static createFrom($$source: any = {}): CredentialUpdateEnvelope {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField4_0($$parsedSource["error"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField5_0($$parsedSource["result"]);
        }
        return new CredentialUpdateEnvelope($$parsedSource as Partial<CredentialUpdateEnvelope>);
    }
}

export class CredentialUpdateRequest {
    "selectionId": SelectionID;
    "verificationFlow"?: model$0.VerificationFlow;
    "credentialIdHex": string;
    "userIdHex"?: string;
    "name"?: string;
    "displayName"?: string;
    "userIdProvided"?: boolean;
    "nameProvided"?: boolean;
    "displayProvided"?: boolean;
    "confirmed"?: boolean;
    "confirmationMessage"?: string;
    "dryRun"?: boolean;

    /** Creates a new CredentialUpdateRequest instance. */
    constructor($$source: Partial<CredentialUpdateRequest> = {}) {
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }
        if (!("credentialIdHex" in $$source)) {
            this["credentialIdHex"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CredentialUpdateRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CredentialUpdateRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CredentialUpdateRequest($$parsedSource as Partial<CredentialUpdateRequest>);
    }
}

export class CredentialsEnvelope {
    "operationId": OperationID;
    "selectionId": SelectionID;
    "kind": model$0.OperationKind;
    "authenticatorClosed": boolean;
    "error"?: failure$0.Failure | null;
    "result"?: model$0.CredentialsOutput | null;

    /** Creates a new CredentialsEnvelope instance. */
    constructor($$source: Partial<CredentialsEnvelope> = {}) {
        if (!("operationId" in $$source)) {
            this["operationId"] = "";
        }
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = model$0.OperationKind.$zero;
        }
        if (!("authenticatorClosed" in $$source)) {
            this["authenticatorClosed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CredentialsEnvelope instance from a string or object.
     */
    static createFrom($$source: any = {}): CredentialsEnvelope {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType21;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField4_0($$parsedSource["error"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField5_0($$parsedSource["result"]);
        }
        return new CredentialsEnvelope($$parsedSource as Partial<CredentialsEnvelope>);
    }
}

export class DiscoverRequest {
    "mode"?: transport$0.Mode;

    /** Creates a new DiscoverRequest instance. */
    constructor($$source: Partial<DiscoverRequest> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiscoverRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): DiscoverRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiscoverRequest($$parsedSource as Partial<DiscoverRequest>);
    }
}

export class DiscoveryChangedEnvelope {
    "trigger": DiscoveryTrigger;
    "snapshot"?: DiscoverySnapshot | null;
    "error"?: failure$0.Failure | null;

    /** Creates a new DiscoveryChangedEnvelope instance. */
    constructor($$source: Partial<DiscoveryChangedEnvelope> = {}) {
        if (!("trigger" in $$source)) {
            this["trigger"] = DiscoveryTrigger.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiscoveryChangedEnvelope instance from a string or object.
     */
    static createFrom($$source: any = {}): DiscoveryChangedEnvelope {
        const $$createField1_0 = $$createType23;
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("snapshot" in $$parsedSource) {
            $$parsedSource["snapshot"] = $$createField1_0($$parsedSource["snapshot"]);
        }
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField2_0($$parsedSource["error"]);
        }
        return new DiscoveryChangedEnvelope($$parsedSource as Partial<DiscoveryChangedEnvelope>);
    }
}

export class DiscoverySnapshot {
    "devices": report$0.DeviceReport[];

    /** Creates a new DiscoverySnapshot instance. */
    constructor($$source: Partial<DiscoverySnapshot> = {}) {
        if (!("devices" in $$source)) {
            this["devices"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiscoverySnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): DiscoverySnapshot {
        const $$createField0_0 = $$createType25;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("devices" in $$parsedSource) {
            $$parsedSource["devices"] = $$createField0_0($$parsedSource["devices"]);
        }
        return new DiscoverySnapshot($$parsedSource as Partial<DiscoverySnapshot>);
    }
}

export enum DiscoveryTrigger {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DiscoveryTriggerMonitor = "monitor",
    DiscoveryTriggerHotplug = "hotplug",
    DiscoveryTriggerManual = "manual",
    DiscoveryTriggerEnriched = "enriched",
};

export class EnableLongTouchForResetRequest {
    "selectionId": SelectionID;
    "verificationFlow"?: model$0.VerificationFlow;
    "confirmed"?: boolean;
    "confirmationMessage"?: string;
    "dryRun"?: boolean;

    /** Creates a new EnableLongTouchForResetRequest instance. */
    constructor($$source: Partial<EnableLongTouchForResetRequest> = {}) {
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnableLongTouchForResetRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): EnableLongTouchForResetRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EnableLongTouchForResetRequest($$parsedSource as Partial<EnableLongTouchForResetRequest>);
    }
}

export class GetAssertionEnvelope {
    "operationId": OperationID;
    "selectionId": SelectionID;
    "kind": model$0.OperationKind;
    "authenticatorClosed": boolean;
    "error"?: failure$0.Failure | null;
    "result"?: model$0.GetAssertionOutput | null;

    /** Creates a new GetAssertionEnvelope instance. */
    constructor($$source: Partial<GetAssertionEnvelope> = {}) {
        if (!("operationId" in $$source)) {
            this["operationId"] = "";
        }
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = model$0.OperationKind.$zero;
        }
        if (!("authenticatorClosed" in $$source)) {
            this["authenticatorClosed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetAssertionEnvelope instance from a string or object.
     */
    static createFrom($$source: any = {}): GetAssertionEnvelope {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType27;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField4_0($$parsedSource["error"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField5_0($$parsedSource["result"]);
        }
        return new GetAssertionEnvelope($$parsedSource as Partial<GetAssertionEnvelope>);
    }
}

export class GetAssertionRequest {
    "selectionId": SelectionID;
    "verificationFlow"?: model$0.VerificationFlow;
    "rpID": string;
    "clientDataJSON": string;
    "allowList"?: credential$0.PublicKeyCredentialDescriptor[];
    "options"?: webauthn$0.AuthenticatorOptions;
    "extensions"?: webauthn$1.GetAuthenticationExtensionsClientInputs | null;
    "confirmed"?: boolean;
    "confirmationMessage"?: string;
    "dryRun"?: boolean;

    /** Creates a new GetAssertionRequest instance. */
    constructor($$source: Partial<GetAssertionRequest> = {}) {
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }
        if (!("rpID" in $$source)) {
            this["rpID"] = "";
        }
        if (!("clientDataJSON" in $$source)) {
            this["clientDataJSON"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetAssertionRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): GetAssertionRequest {
        const $$createField3_0 = $Create.ByteSlice;
        const $$createField4_0 = $$createType29;
        const $$createField5_0 = $$createType30;
        const $$createField6_0 = $$createType32;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("clientDataJSON" in $$parsedSource) {
            $$parsedSource["clientDataJSON"] = $$createField3_0($$parsedSource["clientDataJSON"]);
        }
        if ("allowList" in $$parsedSource) {
            $$parsedSource["allowList"] = $$createField4_0($$parsedSource["allowList"]);
        }
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField5_0($$parsedSource["options"]);
        }
        if ("extensions" in $$parsedSource) {
            $$parsedSource["extensions"] = $$createField6_0($$parsedSource["extensions"]);
        }
        return new GetAssertionRequest($$parsedSource as Partial<GetAssertionRequest>);
    }
}

export class InspectEnvelope {
    "operationId": OperationID;
    "selectionId": SelectionID;
    "kind": model$0.OperationKind;
    "authenticatorClosed": boolean;
    "error"?: failure$0.Failure | null;
    "result"?: model$0.InspectOutput | null;

    /** Creates a new InspectEnvelope instance. */
    constructor($$source: Partial<InspectEnvelope> = {}) {
        if (!("operationId" in $$source)) {
            this["operationId"] = "";
        }
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = model$0.OperationKind.$zero;
        }
        if (!("authenticatorClosed" in $$source)) {
            this["authenticatorClosed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InspectEnvelope instance from a string or object.
     */
    static createFrom($$source: any = {}): InspectEnvelope {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType34;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField4_0($$parsedSource["error"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField5_0($$parsedSource["result"]);
        }
        return new InspectEnvelope($$parsedSource as Partial<InspectEnvelope>);
    }
}

export class InteractionAnswer {
    "interactionId": InteractionID;
    "pin"?: string;
    "confirmed"?: boolean;
    "canceled"?: boolean;

    /** Creates a new InteractionAnswer instance. */
    constructor($$source: Partial<InteractionAnswer> = {}) {
        if (!("interactionId" in $$source)) {
            this["interactionId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InteractionAnswer instance from a string or object.
     */
    static createFrom($$source: any = {}): InteractionAnswer {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InteractionAnswer($$parsedSource as Partial<InteractionAnswer>);
    }
}

export type InteractionID = string;

export class InteractionPrompt {
    "interactionId": InteractionID;
    "operationId": OperationID;
    "selectionId": SelectionID;
    "request": model$0.InteractionRequest;

    /** Creates a new InteractionPrompt instance. */
    constructor($$source: Partial<InteractionPrompt> = {}) {
        if (!("interactionId" in $$source)) {
            this["interactionId"] = "";
        }
        if (!("operationId" in $$source)) {
            this["operationId"] = "";
        }
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }
        if (!("request" in $$source)) {
            this["request"] = (new model$0.InteractionRequest());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InteractionPrompt instance from a string or object.
     */
    static createFrom($$source: any = {}): InteractionPrompt {
        const $$createField3_0 = $$createType35;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("request" in $$parsedSource) {
            $$parsedSource["request"] = $$createField3_0($$parsedSource["request"]);
        }
        return new InteractionPrompt($$parsedSource as Partial<InteractionPrompt>);
    }
}

export class LargeBlobGarbageCollectRequest {
    "selectionId": SelectionID;
    "verificationFlow"?: model$0.VerificationFlow;
    "confirmed"?: boolean;
    "confirmationMessage"?: string;
    "dryRun"?: boolean;

    /** Creates a new LargeBlobGarbageCollectRequest instance. */
    constructor($$source: Partial<LargeBlobGarbageCollectRequest> = {}) {
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LargeBlobGarbageCollectRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): LargeBlobGarbageCollectRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LargeBlobGarbageCollectRequest($$parsedSource as Partial<LargeBlobGarbageCollectRequest>);
    }
}

export class LargeBlobListEnvelope {
    "operationId": OperationID;
    "selectionId": SelectionID;
    "kind": model$0.OperationKind;
    "authenticatorClosed": boolean;
    "error"?: failure$0.Failure | null;
    "result"?: model$0.LargeBlobListOutput | null;

    /** Creates a new LargeBlobListEnvelope instance. */
    constructor($$source: Partial<LargeBlobListEnvelope> = {}) {
        if (!("operationId" in $$source)) {
            this["operationId"] = "";
        }
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = model$0.OperationKind.$zero;
        }
        if (!("authenticatorClosed" in $$source)) {
            this["authenticatorClosed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LargeBlobListEnvelope instance from a string or object.
     */
    static createFrom($$source: any = {}): LargeBlobListEnvelope {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType37;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField4_0($$parsedSource["error"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField5_0($$parsedSource["result"]);
        }
        return new LargeBlobListEnvelope($$parsedSource as Partial<LargeBlobListEnvelope>);
    }
}

export class LargeBlobListRequest {
    "selectionId": SelectionID;
    "verificationFlow"?: model$0.VerificationFlow;

    /** Creates a new LargeBlobListRequest instance. */
    constructor($$source: Partial<LargeBlobListRequest> = {}) {
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LargeBlobListRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): LargeBlobListRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LargeBlobListRequest($$parsedSource as Partial<LargeBlobListRequest>);
    }
}

export class LargeBlobMutationEnvelope {
    "operationId": OperationID;
    "selectionId": SelectionID;
    "kind": model$0.OperationKind;
    "authenticatorClosed": boolean;
    "error"?: failure$0.Failure | null;
    "result"?: model$0.LargeBlobMutationOutput | null;

    /** Creates a new LargeBlobMutationEnvelope instance. */
    constructor($$source: Partial<LargeBlobMutationEnvelope> = {}) {
        if (!("operationId" in $$source)) {
            this["operationId"] = "";
        }
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = model$0.OperationKind.$zero;
        }
        if (!("authenticatorClosed" in $$source)) {
            this["authenticatorClosed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LargeBlobMutationEnvelope instance from a string or object.
     */
    static createFrom($$source: any = {}): LargeBlobMutationEnvelope {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType39;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField4_0($$parsedSource["error"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField5_0($$parsedSource["result"]);
        }
        return new LargeBlobMutationEnvelope($$parsedSource as Partial<LargeBlobMutationEnvelope>);
    }
}

export class LargeBlobMutationRequest {
    "selectionId": SelectionID;
    "verificationFlow"?: model$0.VerificationFlow;
    "credentialIdHex": string;
    "payload"?: string;
    "confirmed"?: boolean;
    "confirmationMessage"?: string;
    "dryRun"?: boolean;

    /** Creates a new LargeBlobMutationRequest instance. */
    constructor($$source: Partial<LargeBlobMutationRequest> = {}) {
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }
        if (!("credentialIdHex" in $$source)) {
            this["credentialIdHex"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LargeBlobMutationRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): LargeBlobMutationRequest {
        const $$createField3_0 = $Create.ByteSlice;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("payload" in $$parsedSource) {
            $$parsedSource["payload"] = $$createField3_0($$parsedSource["payload"]);
        }
        return new LargeBlobMutationRequest($$parsedSource as Partial<LargeBlobMutationRequest>);
    }
}

export class LargeBlobReadEnvelope {
    "operationId": OperationID;
    "selectionId": SelectionID;
    "kind": model$0.OperationKind;
    "authenticatorClosed": boolean;
    "error"?: failure$0.Failure | null;
    "result"?: model$0.LargeBlobReadOutput | null;

    /** Creates a new LargeBlobReadEnvelope instance. */
    constructor($$source: Partial<LargeBlobReadEnvelope> = {}) {
        if (!("operationId" in $$source)) {
            this["operationId"] = "";
        }
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = model$0.OperationKind.$zero;
        }
        if (!("authenticatorClosed" in $$source)) {
            this["authenticatorClosed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LargeBlobReadEnvelope instance from a string or object.
     */
    static createFrom($$source: any = {}): LargeBlobReadEnvelope {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType41;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField4_0($$parsedSource["error"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField5_0($$parsedSource["result"]);
        }
        return new LargeBlobReadEnvelope($$parsedSource as Partial<LargeBlobReadEnvelope>);
    }
}

export class LargeBlobReadRequest {
    "selectionId": SelectionID;
    "verificationFlow"?: model$0.VerificationFlow;
    "credentialIdHex": string;
    "decodeMode"?: largeblobs$0.DecodeMode;

    /** Creates a new LargeBlobReadRequest instance. */
    constructor($$source: Partial<LargeBlobReadRequest> = {}) {
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }
        if (!("credentialIdHex" in $$source)) {
            this["credentialIdHex"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LargeBlobReadRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): LargeBlobReadRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LargeBlobReadRequest($$parsedSource as Partial<LargeBlobReadRequest>);
    }
}

export class LogCursor {
    "sequence": number;

    /** Creates a new LogCursor instance. */
    constructor($$source: Partial<LogCursor> = {}) {
        if (!("sequence" in $$source)) {
            this["sequence"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogCursor instance from a string or object.
     */
    static createFrom($$source: any = {}): LogCursor {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogCursor($$parsedSource as Partial<LogCursor>);
    }
}

export class MDSLookupEnvelope {
    "result": mds$0.LookupResult;

    /** Creates a new MDSLookupEnvelope instance. */
    constructor($$source: Partial<MDSLookupEnvelope> = {}) {
        if (!("result" in $$source)) {
            this["result"] = (new mds$0.LookupResult());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MDSLookupEnvelope instance from a string or object.
     */
    static createFrom($$source: any = {}): MDSLookupEnvelope {
        const $$createField0_0 = $$createType42;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField0_0($$parsedSource["result"]);
        }
        return new MDSLookupEnvelope($$parsedSource as Partial<MDSLookupEnvelope>);
    }
}

export class MDSLookupRequest {
    "aaguid": string;
    "source"?: string;
    "cacheDir"?: string;
    "refresh"?: boolean;

    /** Creates a new MDSLookupRequest instance. */
    constructor($$source: Partial<MDSLookupRequest> = {}) {
        if (!("aaguid" in $$source)) {
            this["aaguid"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MDSLookupRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): MDSLookupRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MDSLookupRequest($$parsedSource as Partial<MDSLookupRequest>);
    }
}

export class MakeCredentialEnvelope {
    "operationId": OperationID;
    "selectionId": SelectionID;
    "kind": model$0.OperationKind;
    "authenticatorClosed": boolean;
    "error"?: failure$0.Failure | null;
    "result"?: model$0.MakeCredentialOutput | null;

    /** Creates a new MakeCredentialEnvelope instance. */
    constructor($$source: Partial<MakeCredentialEnvelope> = {}) {
        if (!("operationId" in $$source)) {
            this["operationId"] = "";
        }
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = model$0.OperationKind.$zero;
        }
        if (!("authenticatorClosed" in $$source)) {
            this["authenticatorClosed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MakeCredentialEnvelope instance from a string or object.
     */
    static createFrom($$source: any = {}): MakeCredentialEnvelope {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType44;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField4_0($$parsedSource["error"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField5_0($$parsedSource["result"]);
        }
        return new MakeCredentialEnvelope($$parsedSource as Partial<MakeCredentialEnvelope>);
    }
}

export class MakeCredentialRequest {
    "selectionId": SelectionID;
    "verificationFlow"?: model$0.VerificationFlow;
    "rp": credential$0.PublicKeyCredentialRpEntity;
    "user": credential$0.PublicKeyCredentialUserEntity;
    "clientDataJSON": string;
    "pubKeyCredParams": credential$0.PublicKeyCredentialParameters[];
    "excludeList"?: credential$0.PublicKeyCredentialDescriptor[];
    "options"?: webauthn$0.AuthenticatorOptions;
    "extensions"?: webauthn$1.CreateAuthenticationExtensionsClientInputs | null;
    "enterpriseAttestation"?: number;
    "attestationFormatsPreference"?: attestation$0.AttestationStatementFormatIdentifier[];
    "confirmed"?: boolean;
    "confirmationMessage"?: string;
    "dryRun"?: boolean;

    /** Creates a new MakeCredentialRequest instance. */
    constructor($$source: Partial<MakeCredentialRequest> = {}) {
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }
        if (!("rp" in $$source)) {
            this["rp"] = (new credential$0.PublicKeyCredentialRpEntity());
        }
        if (!("user" in $$source)) {
            this["user"] = (new credential$0.PublicKeyCredentialUserEntity());
        }
        if (!("clientDataJSON" in $$source)) {
            this["clientDataJSON"] = "";
        }
        if (!("pubKeyCredParams" in $$source)) {
            this["pubKeyCredParams"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MakeCredentialRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): MakeCredentialRequest {
        const $$createField2_0 = $$createType45;
        const $$createField3_0 = $$createType46;
        const $$createField4_0 = $Create.ByteSlice;
        const $$createField5_0 = $$createType48;
        const $$createField6_0 = $$createType29;
        const $$createField7_0 = $$createType30;
        const $$createField8_0 = $$createType50;
        const $$createField10_0 = $$createType51;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("rp" in $$parsedSource) {
            $$parsedSource["rp"] = $$createField2_0($$parsedSource["rp"]);
        }
        if ("user" in $$parsedSource) {
            $$parsedSource["user"] = $$createField3_0($$parsedSource["user"]);
        }
        if ("clientDataJSON" in $$parsedSource) {
            $$parsedSource["clientDataJSON"] = $$createField4_0($$parsedSource["clientDataJSON"]);
        }
        if ("pubKeyCredParams" in $$parsedSource) {
            $$parsedSource["pubKeyCredParams"] = $$createField5_0($$parsedSource["pubKeyCredParams"]);
        }
        if ("excludeList" in $$parsedSource) {
            $$parsedSource["excludeList"] = $$createField6_0($$parsedSource["excludeList"]);
        }
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField7_0($$parsedSource["options"]);
        }
        if ("extensions" in $$parsedSource) {
            $$parsedSource["extensions"] = $$createField8_0($$parsedSource["extensions"]);
        }
        if ("attestationFormatsPreference" in $$parsedSource) {
            $$parsedSource["attestationFormatsPreference"] = $$createField10_0($$parsedSource["attestationFormatsPreference"]);
        }
        return new MakeCredentialRequest($$parsedSource as Partial<MakeCredentialRequest>);
    }
}

export class MinPINLengthRequest {
    "selectionId": SelectionID;
    "verificationFlow"?: model$0.VerificationFlow;
    "newMinPINLength"?: number | null;
    "minPinLengthRPIDs"?: string[];
    "forceChangePin"?: boolean;
    "pinComplexityPolicy"?: boolean;
    "confirmed"?: boolean;
    "confirmationMessage"?: string;
    "dryRun"?: boolean;

    /** Creates a new MinPINLengthRequest instance. */
    constructor($$source: Partial<MinPINLengthRequest> = {}) {
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MinPINLengthRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): MinPINLengthRequest {
        const $$createField3_0 = $$createType52;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("minPinLengthRPIDs" in $$parsedSource) {
            $$parsedSource["minPinLengthRPIDs"] = $$createField3_0($$parsedSource["minPinLengthRPIDs"]);
        }
        return new MinPINLengthRequest($$parsedSource as Partial<MinPINLengthRequest>);
    }
}

export class OperationEventEnvelope {
    "operationId"?: OperationID;
    "selectionId": SelectionID;
    "event": model$0.OperationEvent;

    /** Creates a new OperationEventEnvelope instance. */
    constructor($$source: Partial<OperationEventEnvelope> = {}) {
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }
        if (!("event" in $$source)) {
            this["event"] = (new model$0.OperationEvent());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OperationEventEnvelope instance from a string or object.
     */
    static createFrom($$source: any = {}): OperationEventEnvelope {
        const $$createField2_0 = $$createType53;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("event" in $$parsedSource) {
            $$parsedSource["event"] = $$createField2_0($$parsedSource["event"]);
        }
        return new OperationEventEnvelope($$parsedSource as Partial<OperationEventEnvelope>);
    }
}

export type OperationID = string;

export class OperationRequest {
    "selectionId": SelectionID;
    "verificationFlow"?: model$0.VerificationFlow;

    /** Creates a new OperationRequest instance. */
    constructor($$source: Partial<OperationRequest> = {}) {
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OperationRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): OperationRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OperationRequest($$parsedSource as Partial<OperationRequest>);
    }
}

export class PINChangeRequest {
    "selectionId": SelectionID;
    "verificationFlow"?: model$0.VerificationFlow;

    /**
     * CurrentPIN and NewPIN participate in JSON transport. Consumers own
     * redaction at the application boundary and must not log or persist them.
     */
    "currentPIN": string;
    "newPIN": string;
    "confirmed"?: boolean;
    "confirmationMessage"?: string;
    "dryRun"?: boolean;

    /** Creates a new PINChangeRequest instance. */
    constructor($$source: Partial<PINChangeRequest> = {}) {
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }
        if (!("currentPIN" in $$source)) {
            this["currentPIN"] = "";
        }
        if (!("newPIN" in $$source)) {
            this["newPIN"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PINChangeRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): PINChangeRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PINChangeRequest($$parsedSource as Partial<PINChangeRequest>);
    }
}

export class PINEnvelope {
    "operationId": OperationID;
    "selectionId": SelectionID;
    "kind": model$0.OperationKind;
    "authenticatorClosed": boolean;
    "error"?: failure$0.Failure | null;
    "result"?: model$0.PINOutput | null;

    /** Creates a new PINEnvelope instance. */
    constructor($$source: Partial<PINEnvelope> = {}) {
        if (!("operationId" in $$source)) {
            this["operationId"] = "";
        }
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = model$0.OperationKind.$zero;
        }
        if (!("authenticatorClosed" in $$source)) {
            this["authenticatorClosed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PINEnvelope instance from a string or object.
     */
    static createFrom($$source: any = {}): PINEnvelope {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType55;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField4_0($$parsedSource["error"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField5_0($$parsedSource["result"]);
        }
        return new PINEnvelope($$parsedSource as Partial<PINEnvelope>);
    }
}

export class PINSetRequest {
    "selectionId": SelectionID;
    "verificationFlow"?: model$0.VerificationFlow;

    /**
     * NewPIN participates in JSON transport. Consumers own redaction at the
     * application boundary and must not log or persist serialized requests.
     */
    "newPIN": string;
    "confirmed"?: boolean;
    "confirmationMessage"?: string;
    "dryRun"?: boolean;

    /** Creates a new PINSetRequest instance. */
    constructor($$source: Partial<PINSetRequest> = {}) {
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }
        if (!("newPIN" in $$source)) {
            this["newPIN"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PINSetRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): PINSetRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PINSetRequest($$parsedSource as Partial<PINSetRequest>);
    }
}

export class ReadLogsRequest {
    "after"?: number;

    /** Creates a new ReadLogsRequest instance. */
    constructor($$source: Partial<ReadLogsRequest> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReadLogsRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ReadLogsRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReadLogsRequest($$parsedSource as Partial<ReadLogsRequest>);
    }
}

export class ResetFactoryEnvelope {
    "operationId": OperationID;
    "selectionId": SelectionID;
    "kind": model$0.OperationKind;
    "authenticatorClosed": boolean;
    "error"?: failure$0.Failure | null;
    "result"?: model$0.ResetFactoryOutput | null;

    /** Creates a new ResetFactoryEnvelope instance. */
    constructor($$source: Partial<ResetFactoryEnvelope> = {}) {
        if (!("operationId" in $$source)) {
            this["operationId"] = "";
        }
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = model$0.OperationKind.$zero;
        }
        if (!("authenticatorClosed" in $$source)) {
            this["authenticatorClosed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResetFactoryEnvelope instance from a string or object.
     */
    static createFrom($$source: any = {}): ResetFactoryEnvelope {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType57;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField4_0($$parsedSource["error"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField5_0($$parsedSource["result"]);
        }
        return new ResetFactoryEnvelope($$parsedSource as Partial<ResetFactoryEnvelope>);
    }
}

export class ResetFactoryRequest {
    "selectionId": SelectionID;
    "verificationFlow"?: model$0.VerificationFlow;
    "confirmed"?: boolean;
    "confirmationMessage"?: string;
    "dryRun"?: boolean;

    /** Creates a new ResetFactoryRequest instance. */
    constructor($$source: Partial<ResetFactoryRequest> = {}) {
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResetFactoryRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ResetFactoryRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResetFactoryRequest($$parsedSource as Partial<ResetFactoryRequest>);
    }
}

export type SelectionID = string;

export class SelectionRequest {
    "selector"?: string;

    /** Creates a new SelectionRequest instance. */
    constructor($$source: Partial<SelectionRequest> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SelectionRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): SelectionRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SelectionRequest($$parsedSource as Partial<SelectionRequest>);
    }
}

export class SelectionSnapshot {
    "selection"?: ActiveSelection | null;

    /** Creates a new SelectionSnapshot instance. */
    constructor($$source: Partial<SelectionSnapshot> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SelectionSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): SelectionSnapshot {
        const $$createField0_0 = $$createType59;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("selection" in $$parsedSource) {
            $$parsedSource["selection"] = $$createField0_0($$parsedSource["selection"]);
        }
        return new SelectionSnapshot($$parsedSource as Partial<SelectionSnapshot>);
    }
}

// Private type creation functions
const $$createType0 = failure$0.Failure.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = model$0.AuthenticatorConfigOutput.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = model$0.BioEnrollOutput.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = model$0.BioListOutput.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = model$0.BioMutationOutput.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = model$0.BioSensorOutput.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = model$0.ConfigStatusOutput.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = model$0.CredentialDeleteOutput.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = model$0.CredentialStoreStateOutput.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = model$0.CredentialUpdateOutput.createFrom;
const $$createType19 = $Create.Nullable($$createType18);
const $$createType20 = model$0.CredentialsOutput.createFrom;
const $$createType21 = $Create.Nullable($$createType20);
const $$createType22 = DiscoverySnapshot.createFrom;
const $$createType23 = $Create.Nullable($$createType22);
const $$createType24 = report$0.DeviceReport.createFrom;
const $$createType25 = $Create.Array($$createType24);
const $$createType26 = model$0.GetAssertionOutput.createFrom;
const $$createType27 = $Create.Nullable($$createType26);
const $$createType28 = credential$0.PublicKeyCredentialDescriptor.createFrom;
const $$createType29 = $Create.Array($$createType28);
const $$createType30 = webauthn$0.AuthenticatorOptions.createFrom;
const $$createType31 = webauthn$1.GetAuthenticationExtensionsClientInputs.createFrom;
const $$createType32 = $Create.Nullable($$createType31);
const $$createType33 = model$0.InspectOutput.createFrom;
const $$createType34 = $Create.Nullable($$createType33);
const $$createType35 = model$0.InteractionRequest.createFrom;
const $$createType36 = model$0.LargeBlobListOutput.createFrom;
const $$createType37 = $Create.Nullable($$createType36);
const $$createType38 = model$0.LargeBlobMutationOutput.createFrom;
const $$createType39 = $Create.Nullable($$createType38);
const $$createType40 = model$0.LargeBlobReadOutput.createFrom;
const $$createType41 = $Create.Nullable($$createType40);
const $$createType42 = mds$0.LookupResult.createFrom;
const $$createType43 = model$0.MakeCredentialOutput.createFrom;
const $$createType44 = $Create.Nullable($$createType43);
const $$createType45 = credential$0.PublicKeyCredentialRpEntity.createFrom;
const $$createType46 = credential$0.PublicKeyCredentialUserEntity.createFrom;
const $$createType47 = credential$0.PublicKeyCredentialParameters.createFrom;
const $$createType48 = $Create.Array($$createType47);
const $$createType49 = webauthn$1.CreateAuthenticationExtensionsClientInputs.createFrom;
const $$createType50 = $Create.Nullable($$createType49);
const $$createType51 = $Create.Array($Create.Any);
const $$createType52 = $Create.Array($Create.Any);
const $$createType53 = model$0.OperationEvent.createFrom;
const $$createType54 = model$0.PINOutput.createFrom;
const $$createType55 = $Create.Nullable($$createType54);
const $$createType56 = model$0.ResetFactoryOutput.createFrom;
const $$createType57 = $Create.Nullable($$createType56);
const $$createType58 = ActiveSelection.createFrom;
const $$createType59 = $Create.Nullable($$createType58);
