// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Kind identifies a typed public authenticator operation.
 */
export enum Kind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    Inspect = "inspect",
    ListCredentials = "credentials.list",
    CredentialStoreState = "credentials.storeState",
    DeleteCredential = "credentials.delete",
    UpdateCredentialUser = "credentials.updateUser",
    ReadLargeBlob = "largeBlobs.read",
    ListLargeBlobs = "largeBlobs.list",
    WriteLargeBlob = "largeBlobs.write",
    DeleteLargeBlob = "largeBlobs.delete",
    GarbageCollectLargeBlobs = "largeBlobs.garbageCollect",
    ConfigStatus = "config.status",
    BioSensorInfo = "config.bio.sensorInfo",
    BioList = "config.bio.list",
    BioEnroll = "config.bio.enroll",
    BioRename = "config.bio.rename",
    BioRemove = "config.bio.remove",
    ResetFactory = "config.reset.factory",
    SetPIN = "config.pin.set",
    ChangePIN = "config.pin.change",
    SetAlwaysUV = "config.alwaysUv.set",
    SetMinPINLength = "config.minPinLength.set",
    EnableLongTouchForReset = "config.longTouchForReset.enable",
    MakeCredential = "webauthn.makeCredential",
    GetAssertion = "webauthn.getAssertion",
};
